dataset: ETTm2
wandb_project: iReflow-E2E
data_path: ETTm2/ETTm2.csv
model_id: ETTm2_96_192
enc_in: 7
dec_in: 7
c_out: 7
d_model: 128
n_heads: 8
e_layers: 2
flow_layers: 3
d_ff: 128
dropout: 0.1
batch_size: 32
lr: 0.0001
epochs: 40
patience: 8
lr_patience: 2
seq_len: 96
pred_len: 192
num_sampling_steps: 5
temperature: 1.0
num_samples: 100
seeds: [2211, 2212, 2213, 2214]
use_relative_space: true
x0_dist: pred_gaussian
