dataset: Traffic
wandb_project: iReflow-E2E
data_path: traffic/traffic.csv
model_id: traffic_96_192
enc_in: 862
dec_in: 862
c_out: 862
d_model: 512
n_heads: 8
e_layers: 4
flow_layers: 3
d_ff: 512
dropout: 0.1
batch_size: 16
lr: 0.00005
epochs: 40
patience: 8
lr_patience: 3
seq_len: 96
pred_len: 192
num_sampling_steps: 5
temperature: 1.0
num_samples: 100
seeds: [2211, 2212, 2213, 2214]
use_relative_space: true
x0_dist: pred_gaussian
