#!/bin/bash

# iReflow运行脚本 - ETTm2数据集
# 使用三阶段流程进行 NUM_SAMPLING_STEPS 敏感性分析

set -euo pipefail

DATASET="ETTm2"
DATA_PATH="ETTm2/ETTm2.csv"
ROOT_PATH="./data/"

MODEL_ID="ETTm2_96_192"
MODEL_NAME="iReflow"
D_FEATURES="M"
ENC_IN=7
DEC_IN=7
C_OUT=7
DES="Exp"
D_MODEL=128
N_HEADS=8
E_LAYERS=2
FLOW_LAYERS=3
D_FF=128
DROPOUT=0.1
USE_RELATIVE_SPACE=True

BATCH_SIZE=32
EPOCHS=40
PATIENCE=8
LR_PATIENCE=2

NUM_SAMPLING_STEPS_LIST="${NUM_SAMPLING_STEPS_LIST:-5}"
TEMPERATURE=1.0
NUM_SAMPLES=100
X0_DIST="pred_gaussian"

SEQ_LEN=96
PRED_LEN=192
HORIZON=1

GPU_ID="${GPU_ID:-2}"
DEVICE="${DEVICE:-cuda:0}"

SEEDS="${SEEDS:-[2020]}"
CHECKPOINTS="./results/runs/iTransformer/"
ITR=1

STAGE2_WANDB_PROJECT="${STAGE2_WANDB_PROJECT:-iReflow-Stage2-Uncertainty}"
STAGE3_WANDB_PROJECT="${STAGE3_WANDB_PROJECT:-iReflow-Stage3-Velocity}"
STAGE2_LR="${STAGE2_LR:-0.0001}"
STAGE3_LR="${STAGE3_LR:-0.0001}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/three_stage_sweep_lib.sh"

run_stage1
run_stage2
run_stage3_sweep
