seeds: [2022, 2023, 2024]
ablation_mode: mean_only
num_sampling_steps: 5
temperature: 1.0
num_samples: 100
x0_dist: pred_gaussian
use_relative_space: true
datasets:
  - dataset: ETTm1
    data_path: ETTm1/ETTm1.csv
    model_id: ETTm1_96_192
    enc_in: 7
    dec_in: 7
    c_out: 7
    d_model: 128
    n_heads: 8
    e_layers: 2
    flow_layers: 3
    d_ff: 128
    dropout: 0.1
    batch_size: 32
    lr: 0.0001
    epochs: 40
    patience: 8
    lr_patience: 2
  - dataset: ETTm2
    data_path: ETTm2/ETTm2.csv
    model_id: ETTm2_96_192
    enc_in: 7
    dec_in: 7
    c_out: 7
    d_model: 128
    n_heads: 8
    e_layers: 2
    flow_layers: 3
    d_ff: 128
    dropout: 0.1
    batch_size: 32
    lr: 0.0001
    epochs: 40
    patience: 8
    lr_patience: 2
  - dataset: Weather
    data_path: weather/weather.csv
    model_id: weather_96_192
    enc_in: 21
    dec_in: 21
    c_out: 21
    d_model: 512
    n_heads: 8
    e_layers: 3
    flow_layers: 3
    d_ff: 512
    dropout: 0.1
    batch_size: 32
    lr: 0.0001
    epochs: 40
    patience: 8
    lr_patience: 2
  - dataset: Electricity
    data_path: electricity/electricity.csv
    model_id: electricity_96_192
    enc_in: 321
    dec_in: 321
    c_out: 321
    d_model: 512
    n_heads: 8
    e_layers: 3
    flow_layers: 3
    d_ff: 512
    dropout: 0.1
    batch_size: 16
    lr: 0.00005
    epochs: 40
    patience: 8
    lr_patience: 3
