"""
Experiment 1: Macro-micro decoupling case study.

This script consumes the `.npz` artifact generated by
`UncertaintyEstimatorPretrainExp.extract_residuals_on_test` and produces three
publication-ready single-panel figures:

1. Raw future trajectories.
2. Predicted macro components (`mu_hat` and `mu_hat ± sigma_hat`).
3. PDN-normalized residual futures.

Selection protocol follows the design in `docs/Analytical_experiments.md`:
  - rank windows by a deterministic drift score;
  - restrict to the high-drift subset;
  - within that subset, pick a compact group whose oracle-normalized residual
    shapes are highly correlated.
"""

from __future__ import annotations

import argparse
import json
import math
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np

try:
    import seaborn as sns
except ImportError:
    sns = None


def _configure_style() -> None:
    mpl.rcParams.update(
        {
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
            "axes.spines.top": False,
            "axes.spines.right": False,
            "axes.titleweight": "semibold",
            "axes.labelsize": 12,
            "axes.titlesize": 13,
            "xtick.labelsize": 10.5,
            "ytick.labelsize": 10.5,
            "legend.fontsize": 10,
            "figure.titlesize": 15,
            "savefig.dpi": 400,
        }
    )
    if sns is not None:
        sns.set_theme(
            style="whitegrid",
            context="paper",
            palette="colorblind",
            rc={
                "axes.facecolor": "#FBFBFC",
                "figure.facecolor": "white",
                "grid.linestyle": "--",
                "grid.alpha": 0.22,
            },
        )
    else:
        plt.style.use("seaborn-v0_8-whitegrid")


def _as_horizon_tensor(arr: np.ndarray, name: str) -> np.ndarray:
    if arr.ndim != 3:
        raise ValueError(f"{name} must be a 3D tensor [N, P, D], got shape={arr.shape}.")
    return np.asarray(arr, dtype=np.float64)


def _as_stats_tensor(arr: np.ndarray, horizon: int, name: str) -> np.ndarray:
    if arr.ndim != 3:
        raise ValueError(f"{name} must be a 3D tensor, got shape={arr.shape}.")
    arr = np.asarray(arr, dtype=np.float64)
    if arr.shape[1] == 1:
        return np.repeat(arr, horizon, axis=1)
    if arr.shape[1] == horizon:
        return arr
    raise ValueError(
        f"{name} must have shape [N, 1, D] or [N, P, D], got shape={arr.shape} with P={horizon}."
    )


def _normalize_minmax(x: np.ndarray, eps: float = 1e-12) -> np.ndarray:
    xmin = float(np.min(x))
    xmax = float(np.max(x))
    if xmax - xmin < eps:
        return np.zeros_like(x, dtype=np.float64)
    return (x - xmin) / (xmax - xmin + eps)


def _safe_corrcoef(x: np.ndarray) -> np.ndarray:
    x = np.asarray(x, dtype=np.float64)
    if x.ndim != 2:
        raise ValueError(f"Expected a 2D matrix for corrcoef, got {x.shape}.")
    centered = x - x.mean(axis=1, keepdims=True)
    norms = np.linalg.norm(centered, axis=1, keepdims=True)
    norms = np.where(norms < 1e-12, 1.0, norms)
    normalized = centered / norms
    corr = normalized @ normalized.T
    return np.clip(corr, -1.0, 1.0)


def _mean_offdiag(corr: np.ndarray) -> float:
    n = corr.shape[0]
    if n <= 1:
        return float("nan")
    mask = ~np.eye(n, dtype=bool)
    return float(np.mean(corr[mask]))


def _top_fraction_indices(scores: np.ndarray, fraction: float, min_count: int) -> np.ndarray:
    n = scores.shape[0]
    k = max(min_count, int(math.ceil(n * fraction)))
    k = min(max(k, 1), n)
    if k == n:
        return np.arange(n, dtype=np.int64)
    idx = np.argpartition(scores, -k)[-k:]
    idx = idx[np.argsort(scores[idx])[::-1]]
    return idx.astype(np.int64)


def _future_stats(y: np.ndarray, eps: float) -> tuple[np.ndarray, np.ndarray]:
    mu_f = np.mean(y, axis=1)
    sigma_f = np.std(y, axis=1)
    sigma_f = np.maximum(sigma_f, eps)
    return mu_f, sigma_f


def _compute_drift_scores(
    y: np.ndarray,
    mu_x: np.ndarray,
    sigma_x: np.ndarray,
    eps: float,
) -> np.ndarray:
    mu_f, sigma_f = _future_stats(y, eps=eps)
    mu_p = mu_x[:, 0, :]
    sigma_p = np.maximum(sigma_x[:, 0, :], eps)
    drift = np.abs(mu_f - mu_p) / (sigma_p + eps)
    drift += np.abs(np.log(sigma_f + eps) - np.log(sigma_p + eps))
    return drift


def _select_feature_dim(
    drift_scores: np.ndarray,
    valid_mask: np.ndarray,
    high_drift_ratio: float,
    min_high_drift_windows: int,
) -> int:
    per_dim_strength = []
    for d in range(drift_scores.shape[1]):
        valid_idx = np.flatnonzero(valid_mask[:, d])
        if valid_idx.size < min_high_drift_windows:
            per_dim_strength.append(float("-inf"))
            continue
        top_local_idx = _top_fraction_indices(
            drift_scores[valid_idx, d],
            fraction=high_drift_ratio,
            min_count=min_high_drift_windows,
        )
        top_idx = valid_idx[top_local_idx]
        per_dim_strength.append(float(np.mean(drift_scores[top_idx, d])))
    if not np.isfinite(np.max(np.asarray(per_dim_strength, dtype=np.float64))):
        raise ValueError(
            "No valid feature dimension remains after filtering degenerate windows. "
            "Relax the variance thresholds or inspect the residual npz."
        )
    return int(np.argmax(np.asarray(per_dim_strength)))


@dataclass
class SelectionResult:
    feature_dim: int
    candidate_indices: np.ndarray
    selected_indices: np.ndarray
    drift_scores: np.ndarray
    oracle_corr: np.ndarray
    raw_corr: np.ndarray
    pdn_corr: np.ndarray
    future_mean: np.ndarray
    future_std: np.ndarray
    effective_min_index_gap: int


def _select_windows(
    y: np.ndarray,
    mu_x: np.ndarray,
    sigma_x: np.ndarray,
    z_pdn: np.ndarray,
    feature_dim: int,
    num_samples: int,
    high_drift_ratio: float,
    min_high_drift_windows: int,
    min_future_std: float,
    min_past_std: float,
    min_index_gap: int,
    eps: float,
) -> SelectionResult:
    drift_scores_all = _compute_drift_scores(y, mu_x, sigma_x, eps=eps)
    drift_scores = drift_scores_all[:, feature_dim]

    y_d = y[:, :, feature_dim]
    z_pdn_d = z_pdn[:, :, feature_dim]

    future_mean = np.mean(y_d, axis=1)
    future_std_raw = np.std(y_d, axis=1)
    future_std = np.maximum(future_std_raw, eps)
    past_std_raw = sigma_x[:, 0, feature_dim]
    oracle_z = (y_d - future_mean[:, None]) / future_std[:, None]

    valid_idx = np.flatnonzero(
        (future_std_raw > min_future_std) & (past_std_raw > min_past_std)
    )
    if valid_idx.size < num_samples:
        raise ValueError(
            f"Feature {feature_dim} has only {valid_idx.size} valid windows after "
            f"filtering, fewer than num_samples={num_samples}."
        )

    candidate_local_idx = _top_fraction_indices(
        drift_scores[valid_idx],
        fraction=high_drift_ratio,
        min_count=max(min_high_drift_windows, num_samples),
    )
    candidate_idx = valid_idx[candidate_local_idx]

    oracle_candidate = oracle_z[candidate_idx]
    corr = _safe_corrcoef(oracle_candidate)
    drift_norm = _normalize_minmax(drift_scores[candidate_idx])

    neighbor_count = min(num_samples - 1, max(candidate_idx.shape[0] - 1, 1))
    if neighbor_count <= 0:
        local_quality = np.zeros(candidate_idx.shape[0], dtype=np.float64)
    else:
        local_quality = []
        for i in range(candidate_idx.shape[0]):
            row = np.delete(corr[i], i)
            top_corr = np.sort(row)[-neighbor_count:]
            local_quality.append(float(np.mean(top_corr)))
        local_quality = np.asarray(local_quality, dtype=np.float64)

    anchor_score = local_quality + 0.20 * drift_norm

    effective_min_index_gap = max(0, int(min_index_gap))
    selected_local: list[int] = []
    current_gap = effective_min_index_gap
    available_order = list(np.argsort(anchor_score)[::-1])

    while len(selected_local) < num_samples:
        added_in_this_round = False
        for anchor in available_order:
            if anchor in selected_local:
                continue
            if any(abs(int(candidate_idx[anchor]) - int(candidate_idx[s])) < current_gap for s in selected_local):
                continue

            if not selected_local:
                selected_local.append(int(anchor))
                added_in_this_round = True
                break

            similarity = float(np.mean(corr[anchor, selected_local]))
            candidate_score = similarity + 0.15 * drift_norm[anchor]
            competing = []
            for remaining in available_order:
                if remaining in selected_local or remaining == anchor:
                    continue
                if any(
                    abs(int(candidate_idx[remaining]) - int(candidate_idx[s])) < current_gap
                    for s in selected_local
                ):
                    continue
                competing_similarity = float(np.mean(corr[remaining, selected_local]))
                competing.append(competing_similarity + 0.15 * drift_norm[remaining])
            if not competing or candidate_score >= max(competing):
                selected_local.append(int(anchor))
                added_in_this_round = True
                break

        if added_in_this_round:
            continue

        if current_gap == 0:
            break
        current_gap = current_gap // 2

    if len(selected_local) < num_samples:
        remaining = [i for i in available_order if i not in selected_local]
        for next_idx in remaining:
            selected_local.append(int(next_idx))
            if len(selected_local) >= num_samples:
                break

    selected_local = np.asarray(selected_local[:num_samples], dtype=np.int64)

    selected_indices = candidate_idx[selected_local]
    order = np.argsort(future_mean[selected_indices])[::-1]
    selected_indices = selected_indices[order]

    raw_corr = _safe_corrcoef(y_d[selected_indices])
    pdn_corr = _safe_corrcoef(z_pdn_d[selected_indices])
    oracle_corr = _safe_corrcoef(oracle_z[selected_indices])

    return SelectionResult(
        feature_dim=feature_dim,
        candidate_indices=candidate_idx,
        selected_indices=selected_indices,
        drift_scores=drift_scores,
        oracle_corr=oracle_corr,
        raw_corr=raw_corr,
        pdn_corr=pdn_corr,
        future_mean=future_mean,
        future_std=future_std,
        effective_min_index_gap=current_gap,
    )


def _label_list(
    selected_indices: np.ndarray,
    drift_scores: np.ndarray,
    precision: int = 2,
) -> list[str]:
    return [
        f"#{int(idx)}  drift={drift_scores[int(idx)]:.{precision}f}"
        for idx in selected_indices
    ]


def _save_metadata(
    path: str,
    dataset_name: str,
    feature_dim: int,
    feature_label: str,
    selection: SelectionResult,
) -> None:
    metrics = {
        "raw_pairwise_corr_mean": _mean_offdiag(selection.raw_corr),
        "pdn_pairwise_corr_mean": _mean_offdiag(selection.pdn_corr),
        "oracle_pairwise_corr_mean": _mean_offdiag(selection.oracle_corr),
    }
    payload: dict[str, Any] = {
        "dataset_name": dataset_name,
        "feature_dim": int(feature_dim),
        "feature_label": feature_label,
        "candidate_count": int(selection.candidate_indices.shape[0]),
        "effective_min_index_gap": int(selection.effective_min_index_gap),
        "selected_indices": [int(v) for v in selection.selected_indices.tolist()],
        "selected_drift_scores": [
            float(selection.drift_scores[int(v)]) for v in selection.selected_indices.tolist()
        ],
        "selected_future_mean": [
            float(selection.future_mean[int(v)]) for v in selection.selected_indices.tolist()
        ],
        "selected_future_std": [
            float(selection.future_std[int(v)]) for v in selection.selected_indices.tolist()
        ],
        "metrics": metrics,
    }
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)


def _resolve_panel_output_paths(output_path: str, experiment_subdir: str) -> dict[str, str]:
    path = Path(output_path)
    suffix = path.suffix or ".pdf"
    stem = path.stem if path.suffix else path.name
    parent = path.parent if str(path.parent) else Path(".")
    parent = parent / experiment_subdir
    return {
        "raw": str(parent / f"{stem}_raw{suffix}"),
        "macro": str(parent / f"{stem}_macro{suffix}"),
        "pdn": str(parent / f"{stem}_pdn{suffix}"),
    }


def plot_decoupling_case_study(
    npz_path: str,
    output_path: str,
    metadata_path: str | None = None,
    dataset_name: str = "Traffic",
    feature_dim: int | None = None,
    feature_label: str | None = None,
    num_samples: int = 6,
    high_drift_ratio: float = 0.2,
    min_high_drift_windows: int = 24,
    experiment_subdir: str = "exp1_decoupling_case_study",
    min_future_std: float = 1e-3,
    min_past_std: float = 1e-3,
    min_index_gap: int | None = None,
    eps: float = 1e-6,
) -> dict[str, Any]:
    data = np.load(npz_path)
    required = {"Y", "mu_X", "sigma_X", "mu_Y_hat", "sigma_Y_hat", "Z_PDN"}
    missing = sorted(required - set(data.files))
    if missing:
        raise KeyError(
            f"{npz_path} is missing keys {missing}. "
            "Please regenerate it with `extract_residuals_on_test`."
        )

    y = _as_horizon_tensor(data["Y"], "Y")
    n_windows, horizon, num_dims = y.shape
    mu_x = _as_stats_tensor(data["mu_X"], horizon=horizon, name="mu_X")
    sigma_x = _as_stats_tensor(data["sigma_X"], horizon=horizon, name="sigma_X")
    mu_hat = _as_stats_tensor(data["mu_Y_hat"], horizon=horizon, name="mu_Y_hat")
    sigma_hat = _as_stats_tensor(data["sigma_Y_hat"], horizon=horizon, name="sigma_Y_hat")
    z_pdn = _as_horizon_tensor(data["Z_PDN"], "Z_PDN")

    if num_samples < 2:
        raise ValueError("num_samples must be at least 2 for a comparative case study.")
    if not (0.0 < high_drift_ratio <= 1.0):
        raise ValueError("high_drift_ratio must be within (0, 1].")
    if min_index_gap is None:
        min_index_gap = horizon
    if min_index_gap < 0:
        raise ValueError("min_index_gap must be non-negative.")

    drift_scores_all = _compute_drift_scores(y, mu_x, sigma_x, eps=eps)
    future_std_all = np.std(y, axis=1)
    past_std_all = sigma_x[:, 0, :]
    valid_mask_all = (future_std_all > min_future_std) & (past_std_all > min_past_std)
    if feature_dim is None:
        feature_dim = _select_feature_dim(
            drift_scores_all,
            valid_mask=valid_mask_all,
            high_drift_ratio=high_drift_ratio,
            min_high_drift_windows=min_high_drift_windows,
        )
    if feature_dim < 0 or feature_dim >= num_dims:
        raise ValueError(f"feature_dim must be in [0, {num_dims - 1}], got {feature_dim}.")

    selection = _select_windows(
        y=y,
        mu_x=mu_x,
        sigma_x=sigma_x,
        z_pdn=z_pdn,
        feature_dim=feature_dim,
        num_samples=num_samples,
        high_drift_ratio=high_drift_ratio,
        min_high_drift_windows=min_high_drift_windows,
        min_future_std=min_future_std,
        min_past_std=min_past_std,
        min_index_gap=min_index_gap,
        eps=eps,
    )

    if feature_label is None:
        feature_label = f"feature {feature_dim}"

    idx = selection.selected_indices
    labels = _label_list(idx, selection.drift_scores)

    y_sel = y[idx, :, feature_dim]
    mu_sel = mu_hat[idx, :, feature_dim]
    sigma_sel = np.maximum(np.abs(sigma_hat[idx, :, feature_dim]), eps)
    z_sel = z_pdn[idx, :, feature_dim]

    horizon_axis = np.arange(1, horizon + 1)
    palette = sns.color_palette("colorblind", n_colors=len(idx)) if sns is not None else plt.cm.tab10(
        np.linspace(0.0, 1.0, len(idx))
    )

    _configure_style()
    y_label_left = "Raw target value"
    y_label_right = "Normalized value"
    y_limits_raw = np.quantile(np.concatenate([y_sel.ravel(), mu_sel.ravel()]), [0.02, 0.98])
    y_padding_raw = 0.08 * (y_limits_raw[1] - y_limits_raw[0] + eps)
    macro_values = np.concatenate(
        [
            mu_sel.ravel(),
            (mu_sel - sigma_sel).ravel(),
            (mu_sel + sigma_sel).ravel(),
        ]
    )
    macro_limits = np.quantile(macro_values, [0.01, 0.99])
    macro_span = float(macro_limits[1] - macro_limits[0])
    macro_sigma_ref = float(np.quantile(sigma_sel.ravel(), 0.9))
    macro_padding = max(0.12 * (macro_span + eps), 1.25 * macro_sigma_ref, eps)
    z_limits = np.quantile(z_sel.ravel(), [0.02, 0.98])
    z_abs = max(abs(z_limits[0]), abs(z_limits[1]))
    z_abs = max(z_abs, 1.5)
    output_paths = _resolve_panel_output_paths(
        output_path=output_path,
        experiment_subdir=experiment_subdir,
    )

    def _make_axis() -> tuple[plt.Figure, plt.Axes]:
        fig, ax = plt.subplots(figsize=(5.2, 4.5), dpi=400, constrained_layout=True)
        ax.set_xlabel("Forecast horizon step")
        ax.grid(True, linestyle="--", alpha=0.22)
        return fig, ax

    fig_raw, ax_raw = _make_axis()
    for color, series, label in zip(palette, y_sel, labels):
        ax_raw.plot(horizon_axis, series, color=color, linewidth=2.2, alpha=0.95, label=label)
    ax_raw.set_ylabel(y_label_left)
    ax_raw.set_ylim(y_limits_raw[0] - y_padding_raw, y_limits_raw[1] + y_padding_raw)
    raw_legend = ax_raw.legend(
        loc="lower center",
        ncol=min(len(labels), 2),
        frameon=True,
        framealpha=0.92,
        bbox_to_anchor=(0.5, -0.32),
        columnspacing=1.0,
        handlelength=2.2,
    )
    raw_legend.get_frame().set_edgecolor("#D9DDE3")

    fig_macro, ax_macro = _make_axis()
    for color, mu_series, sigma_series, label in zip(palette, mu_sel, sigma_sel, labels):
        lower = mu_series - sigma_series
        upper = mu_series + sigma_series
        ax_macro.fill_between(horizon_axis, lower, upper, color=color, alpha=0.16, linewidth=0.0)
        ax_macro.plot(horizon_axis, mu_series, color=color, linewidth=2.2, alpha=0.98, label=label)
    ax_macro.set_ylabel(y_label_left)
    ax_macro.set_ylim(macro_limits[0] - macro_padding, macro_limits[1] + macro_padding)
    macro_legend = ax_macro.legend(
        loc="lower center",
        ncol=min(len(labels), 2),
        frameon=True,
        framealpha=0.92,
        bbox_to_anchor=(0.5, -0.32),
        columnspacing=1.0,
        handlelength=2.2,
    )
    macro_legend.get_frame().set_edgecolor("#D9DDE3")

    fig_pdn, ax_pdn = _make_axis()
    for color, series, label in zip(palette, z_sel, labels):
        ax_pdn.plot(horizon_axis, series, color=color, linewidth=2.2, alpha=0.95, label=label)
    ax_pdn.axhline(0.0, color="#303030", linewidth=1.1, linestyle="--", alpha=0.7)
    ax_pdn.set_ylabel(y_label_right)
    ax_pdn.set_ylim(-1.12 * z_abs, 1.12 * z_abs)
    pdn_legend = ax_pdn.legend(
        loc="lower center",
        ncol=min(len(labels), 2),
        frameon=True,
        framealpha=0.92,
        bbox_to_anchor=(0.5, -0.32),
        columnspacing=1.0,
        handlelength=2.2,
    )
    pdn_legend.get_frame().set_edgecolor("#D9DDE3")

    for path in output_paths.values():
        os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    fig_raw.savefig(output_paths["raw"], bbox_inches="tight")
    fig_macro.savefig(output_paths["macro"], bbox_inches="tight")
    fig_pdn.savefig(output_paths["pdn"], bbox_inches="tight")
    plt.close(fig_raw)
    plt.close(fig_macro)
    plt.close(fig_pdn)

    result = {
        "feature_dim": int(feature_dim),
        "feature_label": feature_label,
        "selected_indices": [int(v) for v in idx.tolist()],
        "raw_pairwise_corr_mean": _mean_offdiag(selection.raw_corr),
        "pdn_pairwise_corr_mean": _mean_offdiag(selection.pdn_corr),
        "oracle_pairwise_corr_mean": _mean_offdiag(selection.oracle_corr),
        "candidate_count": int(selection.candidate_indices.shape[0]),
        "experiment_subdir": experiment_subdir,
        "min_future_std": float(min_future_std),
        "min_past_std": float(min_past_std),
        "effective_min_index_gap": int(selection.effective_min_index_gap),
        "output_paths": output_paths,
    }

    if metadata_path is not None:
        _save_metadata(
            path=metadata_path,
            dataset_name=dataset_name,
            feature_dim=feature_dim,
            feature_label=feature_label,
            selection=selection,
        )
    return result


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate the Experiment-1 decoupling case-study figure from residual npz data."
    )
    parser.add_argument(
        "--npz_path",
        type=str,
        required=True,
        help="Path to the residual-analysis `.npz` file generated by `extract_residuals_on_test`.",
    )
    parser.add_argument(
        "--output_path",
        type=str,
        required=True,
        help=(
            "Base output figure path. The script will save "
            "`*_raw.pdf`, `*_macro.pdf`, and `*_pdn.pdf` variants."
        ),
    )
    parser.add_argument(
        "--metadata_path",
        type=str,
        default=None,
        help="Optional JSON path for the deterministic selection metadata.",
    )
    parser.add_argument(
        "--dataset_name",
        type=str,
        default="Traffic",
        help="Dataset name shown in the figure subtitle.",
    )
    parser.add_argument(
        "--feature_dim",
        type=int,
        default=None,
        help="Feature dimension to visualize. Defaults to automatic selection via drift strength.",
    )
    parser.add_argument(
        "--feature_label",
        type=str,
        default=None,
        help="Optional human-readable label for the selected feature.",
    )
    parser.add_argument(
        "--num_samples",
        type=int,
        default=6,
        help="Number of windows shown in the figure.",
    )
    parser.add_argument(
        "--high_drift_ratio",
        type=float,
        default=0.2,
        help="Fraction of highest-drift windows kept as candidates before residual-shape matching.",
    )
    parser.add_argument(
        "--min_high_drift_windows",
        type=int,
        default=24,
        help="Minimum number of high-drift candidates kept before selecting the final figure windows.",
    )
    parser.add_argument(
        "--experiment_subdir",
        type=str,
        default="exp1_decoupling_case_study",
        help="Extra subdirectory inserted under the output directory to separate analytical experiments.",
    )
    parser.add_argument(
        "--min_future_std",
        type=float,
        default=1e-3,
        help="Filter out windows whose future trajectory std is at or below this threshold.",
    )
    parser.add_argument(
        "--min_past_std",
        type=float,
        default=1e-3,
        help="Filter out windows whose past-window scale statistic is at or below this threshold.",
    )
    parser.add_argument(
        "--min_index_gap",
        type=int,
        default=None,
        help=(
            "Minimum distance between selected window indices. "
            "Defaults to the forecast horizon to avoid near-duplicate windows."
        ),
    )
    parser.add_argument(
        "--eps",
        type=float,
        default=1e-6,
        help="Small numerical stabilizer for standard deviations and logs.",
    )
    args = parser.parse_args()

    result = plot_decoupling_case_study(
        npz_path=args.npz_path,
        output_path=args.output_path,
        metadata_path=args.metadata_path,
        dataset_name=args.dataset_name,
        feature_dim=args.feature_dim,
        feature_label=args.feature_label,
        num_samples=args.num_samples,
        high_drift_ratio=args.high_drift_ratio,
        min_high_drift_windows=args.min_high_drift_windows,
        experiment_subdir=args.experiment_subdir,
        min_future_std=args.min_future_std,
        min_past_std=args.min_past_std,
        min_index_gap=args.min_index_gap,
        eps=args.eps,
    )

    print("Saved decoupling case-study figures:")
    for key, path in result["output_paths"].items():
        print(f"  {key}: {path}")
    if args.metadata_path is not None:
        print("Saved selection metadata to:", args.metadata_path)
    print(json.dumps(result, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
