"""
Experiment 2: PCA transport path visualization.

This script consumes the `.npz` artifact generated by
`UncertaintyEstimatorPretrainExp.extract_residuals_on_test` or
`UncertaintyEstimatorPretrainExp.export_decoupling_case_study_data_on_test`
and produces three publication-ready single-panel figures:

1. Raw-space OT path bundle in an independent 2D PCA view.
2. LS-space OT path bundle in an independent 2D PCA view.
3. Endpoint-distance bars along flow time for the same windows and sampled priors.

Design follows `docs/Analytical_experiments.md`:
  - rank test windows by a deterministic drift score;
  - retain the high-drift subset and sample a fixed number of windows;
  - trim extreme LS-endpoint outliers that are dominated by near-zero scales;
  - construct the same OT interpolation path in raw and LS spaces;
  - fit PCA independently per space for visualization;
  - summarize how fast the transport path approaches its terminal state in raw/LS space.
"""

from __future__ import annotations

import argparse
import json
import math
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Optional

import matplotlib as mpl
import matplotlib.colors as mcolors
import matplotlib.pyplot as plt
from matplotlib.patches import Patch
import numpy as np
import torch
from sklearn.decomposition import IncrementalPCA

try:
    from src.analysis.residual_wasserstein import _wasserstein_empirical
except ModuleNotFoundError:
    from residual_wasserstein import _wasserstein_empirical

try:
    import seaborn as sns
except ImportError:
    sns = None


FONT_SCALE = 1.35
PCA_TEXT_SIZE = 12 * FONT_SCALE
MARKER_LINEAR_SCALE = 1.2
MARKER_AREA_SCALE = MARKER_LINEAR_SCALE ** 2
PATH_LINEWIDTH_SCALE = 1.2


def _configure_style() -> None:
    mpl.rcParams.update(
        {
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
            "axes.spines.top": False,
            "axes.spines.right": False,
            "axes.labelsize": 12 * FONT_SCALE,
            "xtick.labelsize": 10.5 * FONT_SCALE,
            "ytick.labelsize": 10.5 * FONT_SCALE,
            "legend.fontsize": 10 * FONT_SCALE,
            "axes.titlesize": 12 * FONT_SCALE,
            "legend.title_fontsize": 10 * FONT_SCALE,
            "savefig.dpi": 600,
        }
    )
    if sns is not None:
        sns.set_theme(
            style="whitegrid",
            context="paper",
            rc={
                "axes.facecolor": "#FBFBFC",
                "figure.facecolor": "white",
                "grid.linestyle": "--",
                "grid.alpha": 0.20,
            },
        )
    else:
        plt.style.use("seaborn-v0_8-whitegrid")


def _as_horizon_tensor(arr: np.ndarray, name: str) -> np.ndarray:
    if arr.ndim != 3:
        raise ValueError(f"{name} must be a 3D tensor [N, P, D], got shape={arr.shape}.")
    return np.asarray(arr, dtype=np.float32)


def _as_stats_tensor(arr: np.ndarray, horizon: int, name: str) -> np.ndarray:
    if arr.ndim != 3:
        raise ValueError(f"{name} must be a 3D tensor, got shape={arr.shape}.")
    arr = np.asarray(arr, dtype=np.float32)
    if arr.shape[1] == 1:
        return np.repeat(arr, horizon, axis=1)
    if arr.shape[1] == horizon:
        return arr
    raise ValueError(
        f"{name} must have shape [N, 1, D] or [N, P, D], got shape={arr.shape} with P={horizon}."
    )


def _top_fraction_indices(scores: np.ndarray, fraction: float, min_count: int) -> np.ndarray:
    n = scores.shape[0]
    k = max(min_count, int(math.ceil(n * fraction)))
    k = min(max(k, 1), n)
    if k == n:
        return np.arange(n, dtype=np.int64)
    idx = np.argpartition(scores, -k)[-k:]
    idx = idx[np.argsort(scores[idx])[::-1]]
    return idx.astype(np.int64)


def _future_stats(y: np.ndarray, eps: float) -> tuple[np.ndarray, np.ndarray]:
    mu_f = np.mean(y, axis=1)
    sigma_f = np.maximum(np.std(y, axis=1), eps)
    return mu_f, sigma_f


def _compute_drift_scores(
    y: np.ndarray,
    mu_x: np.ndarray,
    sigma_x: np.ndarray,
    eps: float,
) -> np.ndarray:
    mu_f, sigma_f = _future_stats(y, eps=eps)
    mu_p = mu_x[:, 0, :]
    sigma_p = np.maximum(sigma_x[:, 0, :], eps)
    drift = np.abs(mu_f - mu_p) / (sigma_p + eps)
    drift += np.abs(np.log(sigma_f + eps) - np.log(sigma_p + eps))
    return drift


@dataclass
class WindowSelection:
    drift_scores: np.ndarray
    candidate_indices: np.ndarray
    selected_indices: np.ndarray
    candidate_indices_before_outlier_filter: np.ndarray | None = None
    outlier_scores: np.ndarray | None = None
    outlier_threshold: float | None = None
    outlier_quantile: float | None = None


def _compute_normalized_endpoint_rms(
    y: np.ndarray,
    mu_hat: np.ndarray,
    sigma_hat: np.ndarray,
) -> np.ndarray:
    z_target = (y - mu_hat) / sigma_hat
    return np.sqrt(np.mean(np.square(z_target, dtype=np.float32), axis=(1, 2), dtype=np.float32))


def _select_windows(
    y: np.ndarray,
    mu_x: np.ndarray,
    sigma_x: np.ndarray,
    mu_hat: np.ndarray,
    sigma_hat: np.ndarray,
    num_windows: int,
    high_drift_ratio: float,
    min_high_drift_windows: int,
    seed: int,
    eps: float,
    drift_feature_dim: int | None = None,
    normalized_outlier_quantile: float = 1.0,
) -> WindowSelection:
    drift_scores_all = _compute_drift_scores(y=y, mu_x=mu_x, sigma_x=sigma_x, eps=eps)
    if drift_feature_dim is None:
        window_scores = drift_scores_all.mean(axis=1)
    else:
        if drift_feature_dim < 0 or drift_feature_dim >= drift_scores_all.shape[1]:
            raise ValueError(
                f"drift_feature_dim must be in [0, {drift_scores_all.shape[1] - 1}], "
                f"got {drift_feature_dim}."
            )
        window_scores = drift_scores_all[:, drift_feature_dim]

    candidate_idx = _top_fraction_indices(
        window_scores,
        fraction=high_drift_ratio,
        min_count=max(min_high_drift_windows, num_windows),
    )
    candidate_idx_before_filter = candidate_idx.copy()
    outlier_scores_all = _compute_normalized_endpoint_rms(y=y, mu_hat=mu_hat, sigma_hat=sigma_hat)
    outlier_threshold = None
    if normalized_outlier_quantile < 1.0:
        if not (0.0 < normalized_outlier_quantile < 1.0):
            raise ValueError("normalized_outlier_quantile must be within (0, 1] when enabled.")
        candidate_outlier_scores = outlier_scores_all[candidate_idx]
        outlier_threshold = float(
            np.quantile(candidate_outlier_scores, normalized_outlier_quantile)
        )
        keep_mask = candidate_outlier_scores <= outlier_threshold
        if int(np.sum(keep_mask)) < num_windows:
            keep_order = np.argsort(candidate_outlier_scores)
            keep_idx = keep_order[:num_windows]
            keep_mask = np.zeros_like(candidate_outlier_scores, dtype=bool)
            keep_mask[keep_idx] = True
            outlier_threshold = float(candidate_outlier_scores[keep_idx[-1]])
        candidate_idx = candidate_idx[keep_mask]

    rng = np.random.default_rng(seed)
    if candidate_idx.shape[0] <= num_windows:
        selected = candidate_idx.copy()
    else:
        selected = rng.choice(candidate_idx, size=num_windows, replace=False)
        order = np.argsort(window_scores[selected])[::-1]
        selected = selected[order]

    return WindowSelection(
        drift_scores=window_scores.astype(np.float64),
        candidate_indices=candidate_idx,
        selected_indices=selected.astype(np.int64),
        candidate_indices_before_outlier_filter=candidate_idx_before_filter.astype(np.int64),
        outlier_scores=outlier_scores_all.astype(np.float64),
        outlier_threshold=outlier_threshold,
        outlier_quantile=None if normalized_outlier_quantile >= 1.0 else normalized_outlier_quantile,
    )


def _resolve_panel_output_paths(output_path: str, experiment_subdir: str) -> dict[str, str]:
    path = Path(output_path)
    suffix = path.suffix or ".pdf"
    stem = path.stem if path.suffix else path.name
    parent = path.parent if str(path.parent) else Path(".")
    parent = parent / experiment_subdir
    return {
        "raw_pca": str(parent / f"{stem}_raw_pca{suffix}"),
        "ls_pca": str(parent / f"{stem}_ls_pca{suffix}"),
        "endpoint_distance": str(parent / f"{stem}_endpoint_distance{suffix}"),
    }


def _iter_state_batches(
    space: str,
    y: np.ndarray,
    mu_hat: np.ndarray,
    sigma_hat: np.ndarray,
    noise: np.ndarray,
    tau_values: np.ndarray,
    batch_size: int,
    flatten_dtype: np.dtype = np.float32,
) -> Iterable[np.ndarray]:
    num_windows = y.shape[0]
    z_target = (y - mu_hat) / sigma_hat
    for tau in tau_values:
        tau_f = np.float32(tau)
        one_minus_tau = np.float32(1.0 - tau)
        for start in range(0, num_windows, batch_size):
            end = min(start + batch_size, num_windows)
            if space == "raw":
                x0 = mu_hat[start:end] + sigma_hat[start:end] * noise[start:end]
                batch = tau_f * y[start:end] + one_minus_tau * x0
            elif space == "pdn":
                batch = tau_f * z_target[start:end] + one_minus_tau * noise[start:end]
            else:
                raise ValueError(f"Unknown space: {space}")
            yield batch.reshape(batch.shape[0], -1).astype(flatten_dtype, copy=False)


def _fit_incremental_pca(
    space: str,
    y: np.ndarray,
    mu_hat: np.ndarray,
    sigma_hat: np.ndarray,
    noise: np.ndarray,
    tau_values: np.ndarray,
    sample_batch_size: int,
    n_components: int,
) -> IncrementalPCA:
    total_states = y.shape[0] * tau_values.shape[0]
    if total_states <= 1:
        raise ValueError("At least two states are required for PCA visualization.")
    n_components = max(2, min(n_components, total_states - 1))
    ipca = IncrementalPCA(n_components=n_components)
    batch_size = max(sample_batch_size, n_components)
    for batch in _iter_state_batches(
        space=space,
        y=y,
        mu_hat=mu_hat,
        sigma_hat=sigma_hat,
        noise=noise,
        tau_values=tau_values,
        batch_size=batch_size,
    ):
        if batch.shape[0] < n_components:
            continue
        ipca.partial_fit(batch)
    return ipca


def _transform_states(
    ipca: IncrementalPCA,
    space: str,
    y: np.ndarray,
    mu_hat: np.ndarray,
    sigma_hat: np.ndarray,
    noise: np.ndarray,
    tau_values: np.ndarray,
    sample_batch_size: int,
) -> np.ndarray:
    transformed_batches = []
    for batch in _iter_state_batches(
        space=space,
        y=y,
        mu_hat=mu_hat,
        sigma_hat=sigma_hat,
        noise=noise,
        tau_values=tau_values,
        batch_size=sample_batch_size,
    ):
        transformed_batches.append(ipca.transform(batch).astype(np.float32, copy=False))
    transformed = np.concatenate(transformed_batches, axis=0)
    num_tau = tau_values.shape[0]
    num_windows = y.shape[0]
    return transformed.reshape(num_tau, num_windows, -1).transpose(1, 0, 2)


def _per_window_wasserstein_to_endpoint(
    state: np.ndarray,
    endpoint: np.ndarray,
) -> np.ndarray:
    state_flat = np.asarray(state, dtype=np.float64).reshape(state.shape[0], -1)
    endpoint_flat = np.asarray(endpoint, dtype=np.float64).reshape(endpoint.shape[0], -1)
    distances = np.asarray(
        [
            _wasserstein_empirical(state_i, endpoint_i)
            for state_i, endpoint_i in zip(state_flat, endpoint_flat)
        ],
        dtype=np.float64,
    )
    return distances


def _upper_iqr_keep_mask(
    values: np.ndarray,
    iqr_multiplier: float = 2.5,
) -> tuple[np.ndarray, float]:
    values = np.asarray(values, dtype=np.float64)
    if values.ndim != 1:
        raise ValueError(f"values must be 1D, got shape={values.shape}.")
    q1, q3 = np.quantile(values, [0.25, 0.75])
    iqr = float(q3 - q1)
    threshold = float(q3 + iqr_multiplier * iqr)
    keep_mask = values <= threshold
    if not np.any(keep_mask):
        keep_mask = np.ones_like(values, dtype=bool)
    return keep_mask, threshold


def _compute_shared_pdn_outlier_filter(
    y: np.ndarray,
    mu_hat: np.ndarray,
    sigma_hat: np.ndarray,
    noise: np.ndarray,
    tau_values: np.ndarray,
    iqr_multiplier: float = 2.5,
) -> dict[str, Any]:
    num_windows = y.shape[0]
    global_keep_mask = np.ones(num_windows, dtype=bool)
    pdn_thresholds = []
    pdn_outlier_counts = []
    pdn_kept_counts = []
    z_target = (y - mu_hat) / sigma_hat

    for tau in tau_values:
        if float(tau) >= 1.0 - 1e-8:
            pdn_thresholds.append(0.0)
            pdn_outlier_counts.append(0)
            pdn_kept_counts.append(int(num_windows))
            continue
        tau_f = np.float32(tau)
        one_minus_tau = np.float32(1.0 - tau)
        pdn_state = tau_f * z_target + one_minus_tau * noise
        pdn_distances = _per_window_wasserstein_to_endpoint(pdn_state, z_target)
        keep_mask_tau, threshold = _upper_iqr_keep_mask(
            pdn_distances,
            iqr_multiplier=iqr_multiplier,
        )
        global_keep_mask &= keep_mask_tau
        pdn_thresholds.append(float(threshold))
        pdn_outlier_counts.append(int(np.size(keep_mask_tau) - np.sum(keep_mask_tau)))
        pdn_kept_counts.append(int(np.sum(keep_mask_tau)))

    if not np.any(global_keep_mask):
        global_keep_mask = np.ones(num_windows, dtype=bool)

    removed_local_indices = np.flatnonzero(~global_keep_mask).astype(np.int64)
    return {
        "keep_mask": global_keep_mask,
        "removed_local_indices": removed_local_indices,
        "removed_count": int(removed_local_indices.shape[0]),
        "kept_count": int(np.sum(global_keep_mask)),
        "pdn_outlier_threshold": pdn_thresholds,
        "pdn_outlier_count": pdn_outlier_counts,
        "pdn_kept_count": pdn_kept_counts,
        "iqr_multiplier": float(iqr_multiplier),
    }


def _compute_endpoint_distance_curves(
    y: np.ndarray,
    mu_hat: np.ndarray,
    sigma_hat: np.ndarray,
    noise: np.ndarray,
    tau_values: np.ndarray,
    shared_keep_mask: np.ndarray | None = None,
) -> dict[str, list[float]]:
    raw_mean_curve = []
    pdn_mean_curve = []
    raw_std_curve = []
    pdn_std_curve = []
    raw_var_curve = []
    pdn_var_curve = []
    raw_mean_unfiltered_curve = []
    pdn_mean_unfiltered_curve = []
    raw_std_unfiltered_curve = []
    pdn_std_unfiltered_curve = []
    raw_var_unfiltered_curve = []
    pdn_var_unfiltered_curve = []
    z_target = (y - mu_hat) / sigma_hat
    if shared_keep_mask is None:
        shared_keep_mask = np.ones(y.shape[0], dtype=bool)
    shared_keep_mask = np.asarray(shared_keep_mask, dtype=bool)
    for tau in tau_values:
        tau_f = np.float32(tau)
        one_minus_tau = np.float32(1.0 - tau)
        raw_state = tau_f * y + one_minus_tau * (mu_hat + sigma_hat * noise)
        pdn_state = tau_f * z_target + one_minus_tau * noise
        raw_distances = _per_window_wasserstein_to_endpoint(raw_state, y)
        pdn_distances = _per_window_wasserstein_to_endpoint(pdn_state, z_target)
        raw_mean_unfiltered_curve.append(float(np.mean(raw_distances, dtype=np.float64)))
        pdn_mean_unfiltered_curve.append(float(np.mean(pdn_distances, dtype=np.float64)))
        raw_std_unfiltered_curve.append(float(np.std(raw_distances, dtype=np.float64)))
        pdn_std_unfiltered_curve.append(float(np.std(pdn_distances, dtype=np.float64)))
        raw_var_unfiltered_curve.append(float(np.var(raw_distances, dtype=np.float64)))
        pdn_var_unfiltered_curve.append(float(np.var(pdn_distances, dtype=np.float64)))

        raw_filtered = raw_distances[shared_keep_mask]
        pdn_filtered = pdn_distances[shared_keep_mask]
        raw_mean_curve.append(float(np.mean(raw_filtered, dtype=np.float64)))
        pdn_mean_curve.append(float(np.mean(pdn_filtered, dtype=np.float64)))
        raw_std_curve.append(float(np.std(raw_filtered, dtype=np.float64)))
        pdn_std_curve.append(float(np.std(pdn_filtered, dtype=np.float64)))
        raw_var_curve.append(float(np.var(raw_filtered, dtype=np.float64)))
        pdn_var_curve.append(float(np.var(pdn_filtered, dtype=np.float64)))
    return {
        "raw": raw_mean_curve,
        "pdn": pdn_mean_curve,
        "raw_std": raw_std_curve,
        "pdn_std": pdn_std_curve,
        "raw_var": raw_var_curve,
        "pdn_var": pdn_var_curve,
        "raw_unfiltered": raw_mean_unfiltered_curve,
        "pdn_unfiltered": pdn_mean_unfiltered_curve,
        "raw_std_unfiltered": raw_std_unfiltered_curve,
        "pdn_std_unfiltered": pdn_std_unfiltered_curve,
        "raw_var_unfiltered": raw_var_unfiltered_curve,
        "pdn_var_unfiltered": pdn_var_unfiltered_curve,
    }


def _tau_colors(num_tau: int) -> list[tuple[float, float, float, float]]:
    if sns is not None:
        palette = sns.color_palette("crest", n_colors=num_tau)
        return [mcolors.to_rgba(color) for color in palette]
    cmap = plt.get_cmap("viridis")
    return [cmap(v) for v in np.linspace(0.18, 0.88, num_tau)]


def _plot_path_bundle(
    coords: np.ndarray,
    tau_values: np.ndarray,
    explained_ratio: np.ndarray,
    output_path: str,
    show_colorbar: bool = True,
    line_alpha: float = 0.22,
    linewidth: float = 0.9,
) -> None:
    fig, ax = plt.subplots(figsize=(6.4, 4.8), dpi=600, constrained_layout=True)
    colors = _tau_colors(len(tau_values))
    for path in coords:
        for tau_idx in range(len(tau_values) - 1):
            segment = path[tau_idx : tau_idx + 2]
            ax.plot(
                segment[:, 0],
                segment[:, 1],
                color=colors[tau_idx + 1],
                alpha=line_alpha,
                linewidth=linewidth * PATH_LINEWIDTH_SCALE,
                solid_capstyle="round",
            )
        ax.scatter(
            path[0, 0],
            path[0, 1],
            s=10 * MARKER_AREA_SCALE,
            color=colors[0],
            alpha=0.30,
            linewidths=0.0,
            marker="o",
            zorder=3,
        )
        ax.scatter(
            path[-1, 0],
            path[-1, 1],
            s=16 * MARKER_AREA_SCALE,
            color=colors[-1],
            alpha=0.42,
            linewidths=0.0,
            marker="^",
            zorder=3,
        )

    centroid_path = coords.mean(axis=0)
    ax.plot(
        centroid_path[:, 0],
        centroid_path[:, 1],
        color="#1F2937",
        linewidth=2.0 * PATH_LINEWIDTH_SCALE,
        alpha=0.90,
        zorder=4,
    )
    ax.scatter(
        centroid_path[0, 0],
        centroid_path[0, 1],
        s=34 * MARKER_AREA_SCALE,
        color="#1F2937",
        marker="o",
        linewidths=0.0,
        zorder=5,
    )
    ax.scatter(
        centroid_path[-1, 0],
        centroid_path[-1, 1],
        s=40 * MARKER_AREA_SCALE,
        color="#1F2937",
        marker="^",
        linewidths=0.0,
        zorder=5,
    )

    ax.set_xlabel(f"PC1 ({100.0 * explained_ratio[0]:.1f}%)", fontsize=PCA_TEXT_SIZE)
    ax.set_ylabel(f"PC2 ({100.0 * explained_ratio[1]:.1f}%)", fontsize=PCA_TEXT_SIZE)
    ax.tick_params(axis="both", labelsize=PCA_TEXT_SIZE)
    ax.grid(True, linestyle="--", alpha=0.20)

    xs = coords[:, :, 0].ravel()
    ys = coords[:, :, 1].ravel()
    x_lo, x_hi = np.quantile(xs, [0.01, 0.99])
    y_lo, y_hi = np.quantile(ys, [0.01, 0.99])
    x_pad = 0.08 * max(x_hi - x_lo, 1e-5)
    y_pad = 0.08 * max(y_hi - y_lo, 1e-5)
    ax.set_xlim(x_lo - x_pad, x_hi + x_pad)
    ax.set_ylim(y_lo - y_pad, y_hi + y_pad)

    if show_colorbar:
        cmap = mcolors.LinearSegmentedColormap.from_list("tau_flow", colors)
        norm = mpl.colors.Normalize(vmin=float(tau_values.min()), vmax=float(tau_values.max()))
        sm = mpl.cm.ScalarMappable(norm=norm, cmap=cmap)
        cbar = fig.colorbar(sm, ax=ax, fraction=0.055, pad=0.03)
        cbar.set_label("Flow time $\\tau$", fontsize=PCA_TEXT_SIZE)
        cbar.ax.tick_params(labelsize=PCA_TEXT_SIZE)

    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    fig.savefig(output_path, bbox_inches="tight")
    plt.close(fig)


def _plot_endpoint_distance_bars(
    tau_values: np.ndarray,
    endpoint_distance: dict[str, list[float]],
    dataset_name: str,
    output_path: str,
) -> None:
    tau_values = np.asarray(tau_values, dtype=np.float64)
    raw_values = np.asarray(endpoint_distance["raw"], dtype=np.float64)
    pdn_values = np.asarray(endpoint_distance["pdn"], dtype=np.float64)
    raw_std = np.asarray(endpoint_distance["raw_std"], dtype=np.float64)
    pdn_std = np.asarray(endpoint_distance["pdn_std"], dtype=np.float64)
    plot_mask = tau_values < (1.0 - 1e-8)
    if not np.any(plot_mask):
        plot_mask = np.ones_like(tau_values, dtype=bool)

    tau_plot = tau_values[plot_mask]
    raw_plot = raw_values[plot_mask]
    pdn_plot = pdn_values[plot_mask]
    raw_std_plot = raw_std[plot_mask]
    pdn_std_plot = pdn_std[plot_mask]

    fig, ax = plt.subplots(figsize=(6.4, 4.8), dpi=600, constrained_layout=True)
    if sns is not None:
        raw_color, pdn_color = sns.color_palette(["#4C78A8", "#D62728"])
    else:
        raw_color, pdn_color = "#4C78A8", "#D62728"

    x = np.arange(tau_plot.shape[0], dtype=np.float64)
    width = 0.26
    raw_bars = ax.bar(
        x - width / 2.0,
        raw_plot,
        width=width,
        color=raw_color,
        edgecolor="white",
        linewidth=0.8,
        hatch="xxx",
        label="Raw Space",
        zorder=3,
    )
    pdn_bars = ax.bar(
        x + width / 2.0,
        pdn_plot,
        width=width,
        color=pdn_color,
        edgecolor="white",
        linewidth=0.8,
        hatch="////",
        label="LS Space",
        zorder=3,
    )
    errorbar_style = {
        "fmt": "none",
        "elinewidth": 1.3,
        "ecolor": "#303030",
        "capsize": 4.0,
        "capthick": 1.3,
        "zorder": 4,
    }
    ax.errorbar(
        x - width / 2.0,
        raw_plot,
        yerr=raw_std_plot,
        **errorbar_style,
    )
    ax.errorbar(
        x + width / 2.0,
        pdn_plot,
        yerr=pdn_std_plot,
        **errorbar_style,
    )

    ax.set_xlabel("Flow time $\\tau$")
    ax.set_ylabel("Mean W1 to Target")
    ax.set_xticks(x)
    ax.set_xticklabels([f"{tau:.2f}" for tau in tau_plot])
    ax.xaxis.label.set_size(PCA_TEXT_SIZE)
    ax.yaxis.label.set_size(PCA_TEXT_SIZE)
    ax.tick_params(axis="both", labelsize=PCA_TEXT_SIZE)
    ax.grid(True, axis="y", linestyle="--", alpha=0.24, zorder=0)
    ax.grid(False, axis="x")

    ymax = float(
        max(
            np.max(raw_plot + raw_std_plot),
            np.max(pdn_plot + pdn_std_plot),
            1e-8,
        )
    )
    ax.set_ylim(0.0, ymax * 1.42)
    ax.margins(x=0.02)

    legend_handles = [
        Patch(facecolor=raw_color, edgecolor="white", linewidth=0.8, hatch="xxx", label="Raw Space"),
        Patch(facecolor=pdn_color, edgecolor="white", linewidth=0.8, hatch="////", label="LS Space"),
    ]
    legend_fontsize = 10.5 * FONT_SCALE
    ax.legend(
        handles=legend_handles,
        loc="upper left",
        frameon=True,
        framealpha=0.95,
        fontsize=legend_fontsize,
    )

    if sns is not None:
        sns.despine(ax=ax, left=False, bottom=False)

    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    fig.savefig(output_path, bbox_inches="tight")
    plt.close(fig)


def _save_metadata(
    path: str,
    dataset_name: str,
    selection: WindowSelection,
    selected_indices: np.ndarray,
    selected_indices_before_shared_filter: np.ndarray,
    shared_pdn_filter: dict[str, Any],
    tau_values: np.ndarray,
    explained_variance_ratio: dict[str, list[float]],
    endpoint_distance: dict[str, list[float]],
    pca_components: int,
    seed: int,
    drift_feature_dim: int | None,
) -> None:
    payload: dict[str, Any] = {
        "dataset_name": dataset_name,
        "seed": int(seed),
        "drift_feature_dim": None if drift_feature_dim is None else int(drift_feature_dim),
        "candidate_count_before_outlier_filter": int(
            selection.candidate_indices_before_outlier_filter.shape[0]
            if selection.candidate_indices_before_outlier_filter is not None
            else selection.candidate_indices.shape[0]
        ),
        "candidate_count": int(selection.candidate_indices.shape[0]),
        "normalized_outlier_quantile": (
            None if selection.outlier_quantile is None else float(selection.outlier_quantile)
        ),
        "normalized_outlier_threshold": (
            None if selection.outlier_threshold is None else float(selection.outlier_threshold)
        ),
        "selected_indices_before_shared_filter": [
            int(v) for v in selected_indices_before_shared_filter.tolist()
        ],
        "selected_indices": [int(v) for v in selected_indices.tolist()],
        "selected_drift_scores": [
            float(selection.drift_scores[int(v)]) for v in selected_indices.tolist()
        ],
        "selected_normalized_endpoint_rms": (
            []
            if selection.outlier_scores is None
            else [float(selection.outlier_scores[int(v)]) for v in selected_indices.tolist()]
        ),
        "tau_values": [float(v) for v in tau_values.tolist()],
        "pca_components": int(pca_components),
        "explained_variance_ratio": explained_variance_ratio,
        "endpoint_distance_metric": "mean_per_window_wasserstein_1d",
        "endpoint_distance_outlier_filter": {
            "space": "ls",
            "rule": "upper_iqr_fence_union_over_tau",
            "iqr_multiplier": float(shared_pdn_filter["iqr_multiplier"]),
            "removed_count": int(shared_pdn_filter["removed_count"]),
            "kept_count": int(shared_pdn_filter["kept_count"]),
            "removed_selected_indices": [
                int(selected_indices_before_shared_filter[int(i)])
                for i in shared_pdn_filter["removed_local_indices"].tolist()
            ],
        },
        "endpoint_distance": {
            "raw": [float(v) for v in endpoint_distance["raw"]],
            "ls": [float(v) for v in endpoint_distance["pdn"]],
            "raw_std": [float(v) for v in endpoint_distance["raw_std"]],
            "ls_std": [float(v) for v in endpoint_distance["pdn_std"]],
            "raw_var": [float(v) for v in endpoint_distance["raw_var"]],
            "ls_var": [float(v) for v in endpoint_distance["pdn_var"]],
            "raw_unfiltered": [float(v) for v in endpoint_distance["raw_unfiltered"]],
            "ls_unfiltered": [float(v) for v in endpoint_distance["pdn_unfiltered"]],
            "raw_std_unfiltered": [float(v) for v in endpoint_distance["raw_std_unfiltered"]],
            "ls_std_unfiltered": [float(v) for v in endpoint_distance["pdn_std_unfiltered"]],
            "raw_var_unfiltered": [float(v) for v in endpoint_distance["raw_var_unfiltered"]],
            "ls_var_unfiltered": [float(v) for v in endpoint_distance["pdn_var_unfiltered"]],
            "ls_outlier_threshold": [float(v) for v in shared_pdn_filter["pdn_outlier_threshold"]],
            "ls_outlier_count": [int(v) for v in shared_pdn_filter["pdn_outlier_count"]],
            "ls_kept_count": [int(v) for v in shared_pdn_filter["pdn_kept_count"]],
        },
    }
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)


def plot_pca_transport_path(
    npz_path: str,
    output_path: str,
    metadata_path: str | None = None,
    dataset_name: str = "Traffic",
    num_windows: int = 256,
    high_drift_ratio: float = 0.2,
    min_high_drift_windows: int = 64,
    tau_values: tuple[float, ...] = (0.0, 0.25, 0.5, 0.75, 1.0),
    seed: int = 42,
    pca_components: int = 8,
    sample_batch_size: int = 64,
    experiment_subdir: str = "exp2_pca_transport_path",
    drift_feature_dim: int | None = None,
    normalized_outlier_quantile: float = 1.0,
    eps: float = 1e-6,
) -> dict[str, Any]:
    data = np.load(npz_path)
    required = {"Y", "mu_X", "sigma_X", "mu_Y_hat", "sigma_Y_hat"}
    missing = sorted(required - set(data.files))
    if missing:
        raise KeyError(
            f"{npz_path} is missing keys {missing}. "
            "Please regenerate it with `extract_residuals_on_test` or "
            "`export_decoupling_case_study_data_on_test`."
        )
    if num_windows < 16:
        raise ValueError("num_windows must be at least 16 for a stable path bundle.")
    if not (0.0 < high_drift_ratio <= 1.0):
        raise ValueError("high_drift_ratio must be within (0, 1].")

    _configure_style()

    y = _as_horizon_tensor(data["Y"], "Y")
    _, horizon, _ = y.shape
    mu_x = _as_stats_tensor(data["mu_X"], horizon=horizon, name="mu_X")
    sigma_x = _as_stats_tensor(data["sigma_X"], horizon=horizon, name="sigma_X")
    mu_hat = _as_stats_tensor(data["mu_Y_hat"], horizon=horizon, name="mu_Y_hat")
    sigma_hat = np.maximum(
        np.abs(_as_stats_tensor(data["sigma_Y_hat"], horizon=horizon, name="sigma_Y_hat")),
        eps,
    )
    tau_arr = np.asarray(tau_values, dtype=np.float32)
    if tau_arr.ndim != 1 or tau_arr.size < 2:
        raise ValueError("tau_values must contain at least two scalars.")

    selection = _select_windows(
        y=y,
        mu_x=mu_x,
        sigma_x=sigma_x,
        mu_hat=mu_hat,
        sigma_hat=sigma_hat,
        num_windows=num_windows,
        high_drift_ratio=high_drift_ratio,
        min_high_drift_windows=min_high_drift_windows,
        seed=seed,
        eps=eps,
        drift_feature_dim=drift_feature_dim,
        normalized_outlier_quantile=normalized_outlier_quantile,
    )
    idx = selection.selected_indices
    idx_before_shared_filter = idx.copy()
    y_selected_all = y[idx_before_shared_filter]
    mu_hat_selected_all = mu_hat[idx_before_shared_filter]
    sigma_hat_selected_all = sigma_hat[idx_before_shared_filter]
    rng = np.random.default_rng(seed)
    noise_selected_all = rng.standard_normal(size=y_selected_all.shape, dtype=np.float32)

    shared_pdn_filter = _compute_shared_pdn_outlier_filter(
        y=y_selected_all,
        mu_hat=mu_hat_selected_all,
        sigma_hat=sigma_hat_selected_all,
        noise=noise_selected_all,
        tau_values=tau_arr,
        iqr_multiplier=2.5,
    )
    shared_keep_mask = shared_pdn_filter["keep_mask"]
    idx = idx_before_shared_filter[shared_keep_mask]
    y_sel = y_selected_all[shared_keep_mask]
    mu_hat_sel = mu_hat_selected_all[shared_keep_mask]
    sigma_hat_sel = sigma_hat_selected_all[shared_keep_mask]
    noise = noise_selected_all[shared_keep_mask]

    raw_ipca = _fit_incremental_pca(
        space="raw",
        y=y_sel,
        mu_hat=mu_hat_sel,
        sigma_hat=sigma_hat_sel,
        noise=noise,
        tau_values=tau_arr,
        sample_batch_size=sample_batch_size,
        n_components=pca_components,
    )
    pdn_ipca = _fit_incremental_pca(
        space="pdn",
        y=y_sel,
        mu_hat=mu_hat_sel,
        sigma_hat=sigma_hat_sel,
        noise=noise,
        tau_values=tau_arr,
        sample_batch_size=sample_batch_size,
        n_components=pca_components,
    )

    raw_coords = _transform_states(
        ipca=raw_ipca,
        space="raw",
        y=y_sel,
        mu_hat=mu_hat_sel,
        sigma_hat=sigma_hat_sel,
        noise=noise,
        tau_values=tau_arr,
        sample_batch_size=sample_batch_size,
    )
    pdn_coords = _transform_states(
        ipca=pdn_ipca,
        space="pdn",
        y=y_sel,
        mu_hat=mu_hat_sel,
        sigma_hat=sigma_hat_sel,
        noise=noise,
        tau_values=tau_arr,
        sample_batch_size=sample_batch_size,
    )

    endpoint_distance = _compute_endpoint_distance_curves(
        y=y_selected_all,
        mu_hat=mu_hat_selected_all,
        sigma_hat=sigma_hat_selected_all,
        noise=noise_selected_all,
        tau_values=tau_arr,
        shared_keep_mask=shared_keep_mask,
    )
    output_paths = _resolve_panel_output_paths(
        output_path=output_path,
        experiment_subdir=experiment_subdir,
    )

    _plot_path_bundle(
        coords=raw_coords[:, :, :2],
        tau_values=tau_arr,
        explained_ratio=raw_ipca.explained_variance_ratio_[:2],
        output_path=output_paths["raw_pca"],
        show_colorbar=False,
    )
    _plot_path_bundle(
        coords=pdn_coords[:, :, :2],
        tau_values=tau_arr,
        explained_ratio=pdn_ipca.explained_variance_ratio_[:2],
        output_path=output_paths["ls_pca"],
        show_colorbar=True,
    )
    _plot_endpoint_distance_bars(
        tau_values=tau_arr,
        endpoint_distance=endpoint_distance,
        dataset_name=dataset_name,
        output_path=output_paths["endpoint_distance"],
    )

    explained_variance_ratio = {
        "raw": [float(v) for v in raw_ipca.explained_variance_ratio_.tolist()],
        "ls": [float(v) for v in pdn_ipca.explained_variance_ratio_.tolist()],
    }
    if metadata_path is not None:
        _save_metadata(
            path=metadata_path,
            dataset_name=dataset_name,
            selection=selection,
            selected_indices=idx,
            selected_indices_before_shared_filter=idx_before_shared_filter,
            shared_pdn_filter=shared_pdn_filter,
            tau_values=tau_arr,
            explained_variance_ratio=explained_variance_ratio,
            endpoint_distance=endpoint_distance,
            pca_components=int(raw_ipca.n_components_),
            seed=seed,
            drift_feature_dim=drift_feature_dim,
        )

    result = {
        "selected_indices": [int(v) for v in idx.tolist()],
        "selected_indices_before_shared_filter": [
            int(v) for v in idx_before_shared_filter.tolist()
        ],
        "candidate_count_before_outlier_filter": int(
            selection.candidate_indices_before_outlier_filter.shape[0]
            if selection.candidate_indices_before_outlier_filter is not None
            else selection.candidate_indices.shape[0]
        ),
        "candidate_count": int(selection.candidate_indices.shape[0]),
        "normalized_outlier_quantile": (
            None if selection.outlier_quantile is None else float(selection.outlier_quantile)
        ),
        "normalized_outlier_threshold": (
            None if selection.outlier_threshold is None else float(selection.outlier_threshold)
        ),
        "tau_values": [float(v) for v in tau_arr.tolist()],
        "pca_components": int(raw_ipca.n_components_),
        "output_paths": output_paths,
        "explained_variance_ratio": explained_variance_ratio,
        "endpoint_distance_metric": "mean_per_window_wasserstein_1d",
        "endpoint_distance_outlier_filter": {
            "space": "ls",
            "rule": "upper_iqr_fence_union_over_tau",
            "iqr_multiplier": float(shared_pdn_filter["iqr_multiplier"]),
            "removed_count": int(shared_pdn_filter["removed_count"]),
            "kept_count": int(shared_pdn_filter["kept_count"]),
            "removed_selected_indices": [
                int(idx_before_shared_filter[int(i)])
                for i in shared_pdn_filter["removed_local_indices"].tolist()
            ],
        },
        "endpoint_distance": {
            "raw": [float(v) for v in endpoint_distance["raw"]],
            "ls": [float(v) for v in endpoint_distance["pdn"]],
            "raw_std": [float(v) for v in endpoint_distance["raw_std"]],
            "ls_std": [float(v) for v in endpoint_distance["pdn_std"]],
            "raw_var": [float(v) for v in endpoint_distance["raw_var"]],
            "ls_var": [float(v) for v in endpoint_distance["pdn_var"]],
            "raw_unfiltered": [float(v) for v in endpoint_distance["raw_unfiltered"]],
            "ls_unfiltered": [float(v) for v in endpoint_distance["pdn_unfiltered"]],
            "raw_std_unfiltered": [float(v) for v in endpoint_distance["raw_std_unfiltered"]],
            "ls_std_unfiltered": [float(v) for v in endpoint_distance["pdn_std_unfiltered"]],
            "raw_var_unfiltered": [float(v) for v in endpoint_distance["raw_var_unfiltered"]],
            "ls_var_unfiltered": [float(v) for v in endpoint_distance["pdn_var_unfiltered"]],
            "ls_outlier_threshold": [float(v) for v in shared_pdn_filter["pdn_outlier_threshold"]],
            "ls_outlier_count": [int(v) for v in shared_pdn_filter["pdn_outlier_count"]],
            "ls_kept_count": [int(v) for v in shared_pdn_filter["pdn_kept_count"]],
        },
    }
    return result


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate analytical figures for transport-path and source-target Wasserstein studies."
    )
    parser.add_argument(
        "--figure_type",
        type=str,
        default="transport_path",
        choices=["transport_path", "source_target_bars"],
        help="Which analysis figure to generate.",
    )
    parser.add_argument(
        "--npz_path",
        type=str,
        default=None,
        help=(
            "Path to the analysis `.npz` file generated by `extract_residuals_on_test` "
            "or `export_decoupling_case_study_data_on_test`."
        ),
    )
    parser.add_argument(
        "--output_path",
        type=str,
        required=True,
        help=(
            "Base output figure path. The script will save "
            "`*_raw_pca.pdf`, `*_ls_pca.pdf`, and a grouped-bar "
            "`*_endpoint_distance.pdf` variant."
        ),
    )
    parser.add_argument(
        "--manifest_path",
        type=str,
        default=None,
        help=(
            "JSON manifest for the cross-method source-target Wasserstein bar figure. "
            "Required when `--figure_type source_target_bars`."
        ),
    )
    parser.add_argument(
        "--metadata_path",
        type=str,
        default=None,
        help="Optional JSON path for deterministic selection metadata and summary metrics.",
    )
    parser.add_argument("--dataset_name", type=str, default="Traffic")
    parser.add_argument("--num_windows", type=int, default=256)
    parser.add_argument("--high_drift_ratio", type=float, default=0.2)
    parser.add_argument("--min_high_drift_windows", type=int, default=64)
    parser.add_argument(
        "--tau_values",
        type=float,
        nargs="+",
        default=[0.0, 0.25, 0.5, 0.75, 1.0],
        help="Flow-time checkpoints used to visualize the OT interpolation path.",
    )
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--pca_components", type=int, default=8)
    parser.add_argument("--sample_batch_size", type=int, default=64)
    parser.add_argument(
        "--experiment_subdir",
        type=str,
        default="exp2_pca_transport_path",
        help="Subdirectory inserted under the output path's parent directory.",
    )
    parser.add_argument(
        "--drift_feature_dim",
        type=int,
        default=None,
        help="Optional feature index used for drift-based window selection. Defaults to mean drift.",
    )
    parser.add_argument(
        "--normalized_outlier_quantile",
        type=float,
        default=1.0,
        help=(
            "Optional upper quantile used to trim extreme LS-endpoint residual RMS values "
            "within the high-drift candidate pool before sampling. Set to 1.0 to disable."
        ),
    )
    parser.add_argument("--eps", type=float, default=1e-6)
    parser.add_argument(
        "--max_points",
        type=int,
        default=250_000,
        help="Maximum number of scalar positions retained per dataset/method for W1 estimation.",
    )
    parser.add_argument(
        "--num_repeats",
        type=int,
        default=8,
        help="Number of Monte Carlo source draws used to estimate mean/std of W1.",
    )
    parser.add_argument(
        "--device",
        type=str,
        default=None,
        help="Optional device override for source-target bar analysis, e.g. `cuda:0`.",
    )
    parser.add_argument(
        "--analysis_batch_size",
        type=int,
        default=None,
        help="Optional batch-size override for source-target bar analysis.",
    )
    parser.add_argument(
        "--analysis_num_worker",
        type=int,
        default=None,
        help="Optional dataloader worker override for source-target bar analysis.",
    )
    parser.add_argument(
        "--analysis_num_samples",
        type=int,
        default=None,
        help="Optional `num_samples` override when reconstructing run configs for analysis.",
    )
    args = parser.parse_args()

    if args.figure_type == "source_target_bars":
        if not args.manifest_path:
            parser.error("--manifest_path is required when --figure_type source_target_bars.")
        try:
            from src.analysis.source_target_w1 import plot_source_target_wasserstein_bars
        except ModuleNotFoundError:
            from source_target_w1 import plot_source_target_wasserstein_bars

        result = plot_source_target_wasserstein_bars(
            manifest_path=args.manifest_path,
            output_path=args.output_path,
            metadata_path=args.metadata_path,
            seed=args.seed,
            max_points=args.max_points,
            num_repeats=args.num_repeats,
            eps=args.eps,
            device=args.device,
            batch_size=args.analysis_batch_size,
            num_worker=args.analysis_num_worker,
            num_samples=args.analysis_num_samples,
        )
    else:
        if not args.npz_path:
            parser.error("--npz_path is required when --figure_type transport_path.")
        result = plot_pca_transport_path(
            npz_path=args.npz_path,
            output_path=args.output_path,
            metadata_path=args.metadata_path,
            dataset_name=args.dataset_name,
            num_windows=args.num_windows,
            high_drift_ratio=args.high_drift_ratio,
            min_high_drift_windows=args.min_high_drift_windows,
            tau_values=tuple(args.tau_values),
            seed=args.seed,
            pca_components=args.pca_components,
            sample_batch_size=args.sample_batch_size,
            experiment_subdir=args.experiment_subdir,
            drift_feature_dim=args.drift_feature_dim,
            normalized_outlier_quantile=args.normalized_outlier_quantile,
            eps=args.eps,
        )
    print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
