"""
Experiment 2: PCA transport path visualization.

This script consumes the `.npz` artifact generated by
`UncertaintyEstimatorPretrainExp.extract_residuals_on_test` or
`UncertaintyEstimatorPretrainExp.export_decoupling_case_study_data_on_test`
and produces three publication-ready single-panel figures:

1. Raw-space OT path bundle in an independent 2D PCA view.
2. PDN-space OT path bundle in an independent 2D PCA view.
3. Dispersion along flow time for the same windows and the same sampled priors.

Design follows `docs/Analytical_experiments.md`:
  - rank test windows by a deterministic drift score;
  - retain the high-drift subset and sample a fixed number of windows;
  - construct the same OT interpolation path in raw and PDN spaces;
  - fit PCA independently per space for visualization.
"""

from __future__ import annotations

import argparse
import json
import math
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable

import matplotlib as mpl
import matplotlib.colors as mcolors
import matplotlib.pyplot as plt
import numpy as np
from sklearn.decomposition import IncrementalPCA

try:
    import seaborn as sns
except ImportError:
    sns = None


def _configure_style() -> None:
    mpl.rcParams.update(
        {
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
            "axes.spines.top": False,
            "axes.spines.right": False,
            "axes.labelsize": 12,
            "xtick.labelsize": 10.5,
            "ytick.labelsize": 10.5,
            "legend.fontsize": 10,
            "savefig.dpi": 400,
        }
    )
    if sns is not None:
        sns.set_theme(
            style="whitegrid",
            context="paper",
            rc={
                "axes.facecolor": "#FBFBFC",
                "figure.facecolor": "white",
                "grid.linestyle": "--",
                "grid.alpha": 0.20,
            },
        )
    else:
        plt.style.use("seaborn-v0_8-whitegrid")


def _as_horizon_tensor(arr: np.ndarray, name: str) -> np.ndarray:
    if arr.ndim != 3:
        raise ValueError(f"{name} must be a 3D tensor [N, P, D], got shape={arr.shape}.")
    return np.asarray(arr, dtype=np.float32)


def _as_stats_tensor(arr: np.ndarray, horizon: int, name: str) -> np.ndarray:
    if arr.ndim != 3:
        raise ValueError(f"{name} must be a 3D tensor, got shape={arr.shape}.")
    arr = np.asarray(arr, dtype=np.float32)
    if arr.shape[1] == 1:
        return np.repeat(arr, horizon, axis=1)
    if arr.shape[1] == horizon:
        return arr
    raise ValueError(
        f"{name} must have shape [N, 1, D] or [N, P, D], got shape={arr.shape} with P={horizon}."
    )


def _top_fraction_indices(scores: np.ndarray, fraction: float, min_count: int) -> np.ndarray:
    n = scores.shape[0]
    k = max(min_count, int(math.ceil(n * fraction)))
    k = min(max(k, 1), n)
    if k == n:
        return np.arange(n, dtype=np.int64)
    idx = np.argpartition(scores, -k)[-k:]
    idx = idx[np.argsort(scores[idx])[::-1]]
    return idx.astype(np.int64)


def _future_stats(y: np.ndarray, eps: float) -> tuple[np.ndarray, np.ndarray]:
    mu_f = np.mean(y, axis=1)
    sigma_f = np.maximum(np.std(y, axis=1), eps)
    return mu_f, sigma_f


def _compute_drift_scores(
    y: np.ndarray,
    mu_x: np.ndarray,
    sigma_x: np.ndarray,
    eps: float,
) -> np.ndarray:
    mu_f, sigma_f = _future_stats(y, eps=eps)
    mu_p = mu_x[:, 0, :]
    sigma_p = np.maximum(sigma_x[:, 0, :], eps)
    drift = np.abs(mu_f - mu_p) / (sigma_p + eps)
    drift += np.abs(np.log(sigma_f + eps) - np.log(sigma_p + eps))
    return drift


@dataclass
class WindowSelection:
    drift_scores: np.ndarray
    candidate_indices: np.ndarray
    selected_indices: np.ndarray


def _select_windows(
    y: np.ndarray,
    mu_x: np.ndarray,
    sigma_x: np.ndarray,
    num_windows: int,
    high_drift_ratio: float,
    min_high_drift_windows: int,
    seed: int,
    eps: float,
    drift_feature_dim: int | None = None,
) -> WindowSelection:
    drift_scores_all = _compute_drift_scores(y=y, mu_x=mu_x, sigma_x=sigma_x, eps=eps)
    if drift_feature_dim is None:
        window_scores = drift_scores_all.mean(axis=1)
    else:
        if drift_feature_dim < 0 or drift_feature_dim >= drift_scores_all.shape[1]:
            raise ValueError(
                f"drift_feature_dim must be in [0, {drift_scores_all.shape[1] - 1}], "
                f"got {drift_feature_dim}."
            )
        window_scores = drift_scores_all[:, drift_feature_dim]

    candidate_idx = _top_fraction_indices(
        window_scores,
        fraction=high_drift_ratio,
        min_count=max(min_high_drift_windows, num_windows),
    )
    rng = np.random.default_rng(seed)
    if candidate_idx.shape[0] <= num_windows:
        selected = candidate_idx.copy()
    else:
        selected = rng.choice(candidate_idx, size=num_windows, replace=False)
        order = np.argsort(window_scores[selected])[::-1]
        selected = selected[order]

    return WindowSelection(
        drift_scores=window_scores.astype(np.float64),
        candidate_indices=candidate_idx,
        selected_indices=selected.astype(np.int64),
    )


def _resolve_panel_output_paths(output_path: str, experiment_subdir: str) -> dict[str, str]:
    path = Path(output_path)
    suffix = path.suffix or ".pdf"
    stem = path.stem if path.suffix else path.name
    parent = path.parent if str(path.parent) else Path(".")
    parent = parent / experiment_subdir
    return {
        "raw_pca": str(parent / f"{stem}_raw_pca{suffix}"),
        "pdn_pca": str(parent / f"{stem}_pdn_pca{suffix}"),
        "dispersion": str(parent / f"{stem}_dispersion{suffix}"),
    }


def _iter_state_batches(
    space: str,
    y: np.ndarray,
    mu_hat: np.ndarray,
    sigma_hat: np.ndarray,
    noise: np.ndarray,
    tau_values: np.ndarray,
    batch_size: int,
    flatten_dtype: np.dtype = np.float32,
) -> Iterable[np.ndarray]:
    num_windows = y.shape[0]
    z_target = (y - mu_hat) / sigma_hat
    for tau in tau_values:
        tau_f = np.float32(tau)
        one_minus_tau = np.float32(1.0 - tau)
        for start in range(0, num_windows, batch_size):
            end = min(start + batch_size, num_windows)
            if space == "raw":
                x0 = mu_hat[start:end] + sigma_hat[start:end] * noise[start:end]
                batch = tau_f * y[start:end] + one_minus_tau * x0
            elif space == "pdn":
                batch = tau_f * z_target[start:end] + one_minus_tau * noise[start:end]
            else:
                raise ValueError(f"Unknown space: {space}")
            yield batch.reshape(batch.shape[0], -1).astype(flatten_dtype, copy=False)


def _fit_incremental_pca(
    space: str,
    y: np.ndarray,
    mu_hat: np.ndarray,
    sigma_hat: np.ndarray,
    noise: np.ndarray,
    tau_values: np.ndarray,
    sample_batch_size: int,
    n_components: int,
) -> IncrementalPCA:
    total_states = y.shape[0] * tau_values.shape[0]
    if total_states <= 1:
        raise ValueError("At least two states are required for PCA visualization.")
    n_components = max(2, min(n_components, total_states - 1))
    ipca = IncrementalPCA(n_components=n_components)
    batch_size = max(sample_batch_size, n_components)
    for batch in _iter_state_batches(
        space=space,
        y=y,
        mu_hat=mu_hat,
        sigma_hat=sigma_hat,
        noise=noise,
        tau_values=tau_values,
        batch_size=batch_size,
    ):
        if batch.shape[0] < n_components:
            continue
        ipca.partial_fit(batch)
    return ipca


def _transform_states(
    ipca: IncrementalPCA,
    space: str,
    y: np.ndarray,
    mu_hat: np.ndarray,
    sigma_hat: np.ndarray,
    noise: np.ndarray,
    tau_values: np.ndarray,
    sample_batch_size: int,
) -> np.ndarray:
    transformed_batches = []
    for batch in _iter_state_batches(
        space=space,
        y=y,
        mu_hat=mu_hat,
        sigma_hat=sigma_hat,
        noise=noise,
        tau_values=tau_values,
        batch_size=sample_batch_size,
    ):
        transformed_batches.append(ipca.transform(batch).astype(np.float32, copy=False))
    transformed = np.concatenate(transformed_batches, axis=0)
    num_tau = tau_values.shape[0]
    num_windows = y.shape[0]
    return transformed.reshape(num_tau, num_windows, -1).transpose(1, 0, 2)


def _pairwise_mean_distance(x: np.ndarray) -> float:
    x = np.asarray(x, dtype=np.float32)
    gram = x @ x.T
    sq_norm = np.sum(x * x, axis=1, keepdims=True)
    dist_sq = np.maximum(sq_norm + sq_norm.T - 2.0 * gram, 0.0)
    upper = np.triu_indices(dist_sq.shape[0], k=1)
    if upper[0].size == 0:
        return 0.0
    return float(np.mean(np.sqrt(dist_sq[upper], dtype=np.float32)))


def _compute_dispersion_curves(
    y: np.ndarray,
    mu_hat: np.ndarray,
    sigma_hat: np.ndarray,
    noise: np.ndarray,
    tau_values: np.ndarray,
) -> dict[str, list[float]]:
    raw_curve = []
    pdn_curve = []
    z_target = (y - mu_hat) / sigma_hat
    for tau in tau_values:
        tau_f = np.float32(tau)
        one_minus_tau = np.float32(1.0 - tau)
        raw_state = tau_f * y + one_minus_tau * (mu_hat + sigma_hat * noise)
        pdn_state = tau_f * z_target + one_minus_tau * noise
        raw_curve.append(_pairwise_mean_distance(raw_state.reshape(raw_state.shape[0], -1)))
        pdn_curve.append(_pairwise_mean_distance(pdn_state.reshape(pdn_state.shape[0], -1)))
    return {"raw": raw_curve, "pdn": pdn_curve}


def _tau_colors(num_tau: int) -> list[tuple[float, float, float, float]]:
    if sns is not None:
        palette = sns.color_palette("crest", n_colors=num_tau)
        return [mcolors.to_rgba(color) for color in palette]
    cmap = plt.get_cmap("viridis")
    return [cmap(v) for v in np.linspace(0.18, 0.88, num_tau)]


def _plot_path_bundle(
    coords: np.ndarray,
    tau_values: np.ndarray,
    explained_ratio: np.ndarray,
    output_path: str,
    line_alpha: float = 0.22,
    linewidth: float = 0.9,
) -> None:
    fig, ax = plt.subplots(figsize=(5.4, 4.7), dpi=400, constrained_layout=True)
    colors = _tau_colors(len(tau_values))
    for path in coords:
        for tau_idx in range(len(tau_values) - 1):
            segment = path[tau_idx : tau_idx + 2]
            ax.plot(
                segment[:, 0],
                segment[:, 1],
                color=colors[tau_idx + 1],
                alpha=line_alpha,
                linewidth=linewidth,
                solid_capstyle="round",
            )
        ax.scatter(
            path[0, 0],
            path[0, 1],
            s=10,
            color=colors[0],
            alpha=0.30,
            linewidths=0.0,
            marker="o",
            zorder=3,
        )
        ax.scatter(
            path[-1, 0],
            path[-1, 1],
            s=16,
            color=colors[-1],
            alpha=0.42,
            linewidths=0.0,
            marker="^",
            zorder=3,
        )

    centroid_path = coords.mean(axis=0)
    ax.plot(
        centroid_path[:, 0],
        centroid_path[:, 1],
        color="#1F2937",
        linewidth=2.0,
        alpha=0.90,
        zorder=4,
    )
    ax.scatter(
        centroid_path[0, 0],
        centroid_path[0, 1],
        s=34,
        color="#1F2937",
        marker="o",
        linewidths=0.0,
        zorder=5,
    )
    ax.scatter(
        centroid_path[-1, 0],
        centroid_path[-1, 1],
        s=40,
        color="#1F2937",
        marker="^",
        linewidths=0.0,
        zorder=5,
    )

    ax.set_xlabel(f"PC1 ({100.0 * explained_ratio[0]:.1f}%)")
    ax.set_ylabel(f"PC2 ({100.0 * explained_ratio[1]:.1f}%)")
    ax.grid(True, linestyle="--", alpha=0.20)

    xs = coords[:, :, 0].ravel()
    ys = coords[:, :, 1].ravel()
    x_lo, x_hi = np.quantile(xs, [0.01, 0.99])
    y_lo, y_hi = np.quantile(ys, [0.01, 0.99])
    x_pad = 0.08 * max(x_hi - x_lo, 1e-5)
    y_pad = 0.08 * max(y_hi - y_lo, 1e-5)
    ax.set_xlim(x_lo - x_pad, x_hi + x_pad)
    ax.set_ylim(y_lo - y_pad, y_hi + y_pad)

    cmap = mcolors.LinearSegmentedColormap.from_list("tau_flow", colors)
    norm = mpl.colors.Normalize(vmin=float(tau_values.min()), vmax=float(tau_values.max()))
    sm = mpl.cm.ScalarMappable(norm=norm, cmap=cmap)
    cbar = fig.colorbar(sm, ax=ax, fraction=0.055, pad=0.03)
    cbar.set_label("Flow time $\\tau$")

    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    fig.savefig(output_path, bbox_inches="tight")
    plt.close(fig)


def _plot_dispersion(
    tau_values: np.ndarray,
    dispersion: dict[str, list[float]],
    output_path: str,
) -> None:
    fig, ax = plt.subplots(figsize=(5.0, 4.3), dpi=400, constrained_layout=True)
    if sns is not None:
        raw_color, pdn_color = sns.color_palette("deep", n_colors=2)
    else:
        raw_color, pdn_color = "#C44E52", "#4C72B0"

    ax.plot(
        tau_values,
        dispersion["raw"],
        color=raw_color,
        linewidth=2.4,
        marker="o",
        markersize=5.6,
        label="Raw space",
    )
    ax.plot(
        tau_values,
        dispersion["pdn"],
        color=pdn_color,
        linewidth=2.4,
        marker="o",
        markersize=5.6,
        label="PDN space",
    )
    ax.set_xlabel("Flow time $\\tau$")
    ax.set_ylabel("Average pairwise distance")
    ax.legend(loc="best", frameon=True, framealpha=0.94)
    ax.grid(True, linestyle="--", alpha=0.20)

    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    fig.savefig(output_path, bbox_inches="tight")
    plt.close(fig)


def _save_metadata(
    path: str,
    dataset_name: str,
    selection: WindowSelection,
    tau_values: np.ndarray,
    explained_variance_ratio: dict[str, list[float]],
    dispersion: dict[str, list[float]],
    pca_components: int,
    seed: int,
    drift_feature_dim: int | None,
) -> None:
    payload: dict[str, Any] = {
        "dataset_name": dataset_name,
        "seed": int(seed),
        "drift_feature_dim": None if drift_feature_dim is None else int(drift_feature_dim),
        "candidate_count": int(selection.candidate_indices.shape[0]),
        "selected_indices": [int(v) for v in selection.selected_indices.tolist()],
        "selected_drift_scores": [
            float(selection.drift_scores[int(v)]) for v in selection.selected_indices.tolist()
        ],
        "tau_values": [float(v) for v in tau_values.tolist()],
        "pca_components": int(pca_components),
        "explained_variance_ratio": explained_variance_ratio,
        "dispersion": {
            "raw": [float(v) for v in dispersion["raw"]],
            "pdn": [float(v) for v in dispersion["pdn"]],
        },
    }
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)


def plot_pca_transport_path(
    npz_path: str,
    output_path: str,
    metadata_path: str | None = None,
    dataset_name: str = "Traffic",
    num_windows: int = 256,
    high_drift_ratio: float = 0.2,
    min_high_drift_windows: int = 64,
    tau_values: tuple[float, ...] = (0.0, 0.25, 0.5, 0.75, 1.0),
    seed: int = 42,
    pca_components: int = 8,
    sample_batch_size: int = 64,
    experiment_subdir: str = "exp2_pca_transport_path",
    drift_feature_dim: int | None = None,
    eps: float = 1e-6,
) -> dict[str, Any]:
    data = np.load(npz_path)
    required = {"Y", "mu_X", "sigma_X", "mu_Y_hat", "sigma_Y_hat"}
    missing = sorted(required - set(data.files))
    if missing:
        raise KeyError(
            f"{npz_path} is missing keys {missing}. "
            "Please regenerate it with `extract_residuals_on_test` or "
            "`export_decoupling_case_study_data_on_test`."
        )
    if num_windows < 16:
        raise ValueError("num_windows must be at least 16 for a stable path bundle.")
    if not (0.0 < high_drift_ratio <= 1.0):
        raise ValueError("high_drift_ratio must be within (0, 1].")

    _configure_style()

    y = _as_horizon_tensor(data["Y"], "Y")
    _, horizon, _ = y.shape
    mu_x = _as_stats_tensor(data["mu_X"], horizon=horizon, name="mu_X")
    sigma_x = _as_stats_tensor(data["sigma_X"], horizon=horizon, name="sigma_X")
    mu_hat = _as_stats_tensor(data["mu_Y_hat"], horizon=horizon, name="mu_Y_hat")
    sigma_hat = np.maximum(
        np.abs(_as_stats_tensor(data["sigma_Y_hat"], horizon=horizon, name="sigma_Y_hat")),
        eps,
    )
    tau_arr = np.asarray(tau_values, dtype=np.float32)
    if tau_arr.ndim != 1 or tau_arr.size < 2:
        raise ValueError("tau_values must contain at least two scalars.")

    selection = _select_windows(
        y=y,
        mu_x=mu_x,
        sigma_x=sigma_x,
        num_windows=num_windows,
        high_drift_ratio=high_drift_ratio,
        min_high_drift_windows=min_high_drift_windows,
        seed=seed,
        eps=eps,
        drift_feature_dim=drift_feature_dim,
    )
    idx = selection.selected_indices
    y_sel = y[idx]
    mu_hat_sel = mu_hat[idx]
    sigma_hat_sel = sigma_hat[idx]
    rng = np.random.default_rng(seed)
    noise = rng.standard_normal(size=y_sel.shape, dtype=np.float32)

    raw_ipca = _fit_incremental_pca(
        space="raw",
        y=y_sel,
        mu_hat=mu_hat_sel,
        sigma_hat=sigma_hat_sel,
        noise=noise,
        tau_values=tau_arr,
        sample_batch_size=sample_batch_size,
        n_components=pca_components,
    )
    pdn_ipca = _fit_incremental_pca(
        space="pdn",
        y=y_sel,
        mu_hat=mu_hat_sel,
        sigma_hat=sigma_hat_sel,
        noise=noise,
        tau_values=tau_arr,
        sample_batch_size=sample_batch_size,
        n_components=pca_components,
    )

    raw_coords = _transform_states(
        ipca=raw_ipca,
        space="raw",
        y=y_sel,
        mu_hat=mu_hat_sel,
        sigma_hat=sigma_hat_sel,
        noise=noise,
        tau_values=tau_arr,
        sample_batch_size=sample_batch_size,
    )
    pdn_coords = _transform_states(
        ipca=pdn_ipca,
        space="pdn",
        y=y_sel,
        mu_hat=mu_hat_sel,
        sigma_hat=sigma_hat_sel,
        noise=noise,
        tau_values=tau_arr,
        sample_batch_size=sample_batch_size,
    )

    dispersion = _compute_dispersion_curves(
        y=y_sel,
        mu_hat=mu_hat_sel,
        sigma_hat=sigma_hat_sel,
        noise=noise,
        tau_values=tau_arr,
    )
    output_paths = _resolve_panel_output_paths(
        output_path=output_path,
        experiment_subdir=experiment_subdir,
    )

    _plot_path_bundle(
        coords=raw_coords[:, :, :2],
        tau_values=tau_arr,
        explained_ratio=raw_ipca.explained_variance_ratio_[:2],
        output_path=output_paths["raw_pca"],
    )
    _plot_path_bundle(
        coords=pdn_coords[:, :, :2],
        tau_values=tau_arr,
        explained_ratio=pdn_ipca.explained_variance_ratio_[:2],
        output_path=output_paths["pdn_pca"],
    )
    _plot_dispersion(
        tau_values=tau_arr,
        dispersion=dispersion,
        output_path=output_paths["dispersion"],
    )

    explained_variance_ratio = {
        "raw": [float(v) for v in raw_ipca.explained_variance_ratio_.tolist()],
        "pdn": [float(v) for v in pdn_ipca.explained_variance_ratio_.tolist()],
    }
    if metadata_path is not None:
        _save_metadata(
            path=metadata_path,
            dataset_name=dataset_name,
            selection=selection,
            tau_values=tau_arr,
            explained_variance_ratio=explained_variance_ratio,
            dispersion=dispersion,
            pca_components=int(raw_ipca.n_components_),
            seed=seed,
            drift_feature_dim=drift_feature_dim,
        )

    return {
        "selected_indices": [int(v) for v in idx.tolist()],
        "candidate_count": int(selection.candidate_indices.shape[0]),
        "tau_values": [float(v) for v in tau_arr.tolist()],
        "pca_components": int(raw_ipca.n_components_),
        "output_paths": output_paths,
        "explained_variance_ratio": explained_variance_ratio,
        "dispersion": {
            "raw": [float(v) for v in dispersion["raw"]],
            "pdn": [float(v) for v in dispersion["pdn"]],
        },
    }


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate Experiment-2 PCA transport path figures from residual npz data."
    )
    parser.add_argument(
        "--npz_path",
        type=str,
        required=True,
        help=(
            "Path to the analysis `.npz` file generated by `extract_residuals_on_test` "
            "or `export_decoupling_case_study_data_on_test`."
        ),
    )
    parser.add_argument(
        "--output_path",
        type=str,
        required=True,
        help=(
            "Base output figure path. The script will save "
            "`*_raw_pca.pdf`, `*_pdn_pca.pdf`, and `*_dispersion.pdf` variants."
        ),
    )
    parser.add_argument(
        "--metadata_path",
        type=str,
        default=None,
        help="Optional JSON path for deterministic selection metadata and summary metrics.",
    )
    parser.add_argument("--dataset_name", type=str, default="Traffic")
    parser.add_argument("--num_windows", type=int, default=256)
    parser.add_argument("--high_drift_ratio", type=float, default=0.2)
    parser.add_argument("--min_high_drift_windows", type=int, default=64)
    parser.add_argument(
        "--tau_values",
        type=float,
        nargs="+",
        default=[0.0, 0.25, 0.5, 0.75, 1.0],
        help="Flow-time checkpoints used to visualize the OT interpolation path.",
    )
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--pca_components", type=int, default=8)
    parser.add_argument("--sample_batch_size", type=int, default=64)
    parser.add_argument(
        "--experiment_subdir",
        type=str,
        default="exp2_pca_transport_path",
        help="Subdirectory inserted under the output path's parent directory.",
    )
    parser.add_argument(
        "--drift_feature_dim",
        type=int,
        default=None,
        help="Optional feature index used for drift-based window selection. Defaults to mean drift.",
    )
    parser.add_argument("--eps", type=float, default=1e-6)
    args = parser.parse_args()

    result = plot_pca_transport_path(
        npz_path=args.npz_path,
        output_path=args.output_path,
        metadata_path=args.metadata_path,
        dataset_name=args.dataset_name,
        num_windows=args.num_windows,
        high_drift_ratio=args.high_drift_ratio,
        min_high_drift_windows=args.min_high_drift_windows,
        tau_values=tuple(args.tau_values),
        seed=args.seed,
        pca_components=args.pca_components,
        sample_batch_size=args.sample_batch_size,
        experiment_subdir=args.experiment_subdir,
        drift_feature_dim=args.drift_feature_dim,
        eps=args.eps,
    )
    print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
