import argparse
import os
from typing import Tuple

import numpy as np
import matplotlib.pyplot as plt

try:
    import seaborn as sns
except ImportError:  # seaborn 可选
    sns = None

try:
    from scipy.stats import norm
except ImportError:
    norm = None


def _flatten_and_clip(
    z: np.ndarray,
    clip_range: Tuple[float, float] | None = (-6.0, 6.0),
) -> Tuple[np.ndarray, float]:
    """
    将 3D 残差张量展平成 1D，并在给定区间内进行截断。

    Args:
        z: 形状 [N, P, D] 的残差张量 (numpy)。
        clip_range: 截断区间 (min, max)。若为 None 则不截断。

    Returns:
        clipped: 展平后并截断的 1D 数组。
        clipped_ratio: 被截断样本占总样本的比例（0~1）。
    """
    z_flat = z.astype(np.float64).ravel()
    if clip_range is None:
        return z_flat, 0.0

    vmin, vmax = clip_range
    before = z_flat.copy()
    z_flat = np.clip(z_flat, vmin, vmax)
    clipped_ratio = float(np.mean((before < vmin) | (before > vmax)))
    return z_flat, clipped_ratio


def plot_residual_histogram(
    npz_path: str,
    output_path: str,
    clip_range: Tuple[float, float] | None = (-6.0, 6.0),
    bins: int = 100,
) -> None:
    """
    从 residual npz 文件中读取 Z_RevIN / Z_PDN，进行展平与截断，并绘制直方图 + 标准正态曲线。

    Args:
        npz_path: `extract_residuals_on_test` 生成的 .npz 路径。
        output_path: 输出图片路径（.png / .pdf 等）。
        clip_range: 残差绘图范围，例如 (-5, 5) 或 (-6, 6)，None 表示不截断。
        bins: 直方图分桶数。
    """
    data = np.load(npz_path)
    if "Z_RevIN" not in data or "Z_PDN" not in data:
        raise KeyError(
            f"{npz_path} 中未找到 'Z_RevIN' / 'Z_PDN'，"
            f"请确认已使用 `extract_residuals_on_test` 生成该文件。"
        )

    z_revin = data["Z_RevIN"]
    z_pdn = data["Z_PDN"]

    z_revin_flat, ratio_revin = _flatten_and_clip(z_revin, clip_range)
    z_pdn_flat, ratio_pdn = _flatten_and_clip(z_pdn, clip_range)

    if clip_range is None:
        xmin = float(min(z_revin_flat.min(), z_pdn_flat.min()))
        xmax = float(max(z_revin_flat.max(), z_pdn_flat.max()))
    else:
        xmin, xmax = clip_range

    # 画布初始化：保证论文级别质量
    plt.close("all")
    fig, ax = plt.subplots(figsize=(8, 4.5), dpi=300)

    # 若有 seaborn，优先用 histplot；否则退回 matplotlib
    if sns is not None:
        sns.histplot(
            z_revin_flat,
            bins=bins,
            stat="density",
            color="tab:red",
            alpha=0.5,
            label="RevIN",
            edgecolor=None,
            ax=ax,
        )
        sns.histplot(
            z_pdn_flat,
            bins=bins,
            stat="density",
            color="tab:blue",
            alpha=0.5,
            label="PDN",
            edgecolor=None,
            ax=ax,
        )
    else:
        ax.hist(
            z_revin_flat,
            bins=bins,
            density=True,
            color="tab:red",
            alpha=0.5,
            label="RevIN",
        )
        ax.hist(
            z_pdn_flat,
            bins=bins,
            density=True,
            color="tab:blue",
            alpha=0.5,
            label="PDN",
        )

    # 叠加标准正态曲线 N(0, 1)
    xs = np.linspace(xmin, xmax, 512)
    if norm is not None:
        ys = norm.pdf(xs, loc=0.0, scale=1.0)
    else:
        # 手写标准正态 pdf，避免强依赖 scipy
        ys = np.exp(-0.5 * xs ** 2) / np.sqrt(2.0 * np.pi)
    ax.plot(xs, ys, "k--", linewidth=2.0, label=r"Standard Normal $\mathcal{N}(0,1)$")

    ax.set_xlabel("Residual Value")
    ax.set_ylabel("Density")
    ax.set_xlim(xmin, xmax)
    ax.legend()
    ax.grid(True, linestyle="--", alpha=0.3)
    fig.tight_layout()

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    fig.savefig(output_path, bbox_inches="tight")

    print(f"Saved residual histogram to: {output_path}")
    if clip_range is not None:
        print(
            f"Clipping range: [{clip_range[0]}, {clip_range[1]}], "
            f"clipped ratio – RevIN: {ratio_revin:.4f}, PDN: {ratio_pdn:.4f}"
        )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Residual flattening, clipping and histogram visualization."
    )
    parser.add_argument(
        "--npz_path",
        type=str,
        default="./results/analysis/electricity_residuals.npz",
        help="Path to the residuals npz file generated by extract_residuals_on_test.",
    )
    parser.add_argument(
        "--output_path",
        type=str,
        default="./results/analysis/electricity_residual_hist.png",
        help="Output image path for the histogram.",
    )
    parser.add_argument(
        "--clip_min",
        type=float,
        default=-6.0,
        help="Minimum residual value for clipping. Set together with --clip_max.",
    )
    parser.add_argument(
        "--clip_max",
        type=float,
        default=6.0,
        help="Maximum residual value for clipping. Set together with --clip_min.",
    )
    parser.add_argument(
        "--no_clip",
        action="store_true",
        help="Disable clipping (use full residual range).",
    )
    parser.add_argument(
        "--bins",
        type=int,
        default=100,
        help="Number of histogram bins.",
    )

    args = parser.parse_args()

    if args.no_clip:
        clip_range = None
    else:
        clip_range = (args.clip_min, args.clip_max)

    plot_residual_histogram(
        npz_path=args.npz_path,
        output_path=args.output_path,
        clip_range=clip_range,
        bins=args.bins,
    )


if __name__ == "__main__":
    main()


